// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xmathfunction.h"

extern XMathfunction_Config XMathfunction_ConfigTable[];

XMathfunction_Config *XMathfunction_LookupConfig(u16 DeviceId) {
	XMathfunction_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XMATHFUNCTION_NUM_INSTANCES; Index++) {
		if (XMathfunction_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XMathfunction_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XMathfunction_Initialize(XMathfunction *InstancePtr, u16 DeviceId) {
	XMathfunction_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XMathfunction_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XMathfunction_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

