// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "simpleALU.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic simpleALU::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic simpleALU::ap_const_logic_0 = sc_dt::Log_0;
const bool simpleALU::ap_const_boolean_1 = true;

simpleALU::simpleALU(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_agg_result_V_assign_fu_42_p2);
    sensitive << ( inA_V );
    sensitive << ( inB_V );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( op_V );
    sensitive << ( agg_result_V_assign_fu_42_p2 );
    sensitive << ( tmp_1_fu_36_p2 );

    SC_METHOD(thread_tmp_1_fu_36_p2);
    sensitive << ( inA_V );
    sensitive << ( inB_V );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "simpleALU_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inA_V, "(port)inA_V");
    sc_trace(mVcdFile, inB_V, "(port)inB_V");
    sc_trace(mVcdFile, op_V, "(port)op_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, agg_result_V_assign_fu_42_p2, "agg_result_V_assign_fu_42_p2");
    sc_trace(mVcdFile, tmp_1_fu_36_p2, "tmp_1_fu_36_p2");
#endif

    }
    mHdltvinHandle.open("simpleALU.hdltvin.dat");
    mHdltvoutHandle.open("simpleALU.hdltvout.dat");
}

simpleALU::~simpleALU() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void simpleALU::thread_agg_result_V_assign_fu_42_p2() {
    agg_result_V_assign_fu_42_p2 = (!inB_V.read().is_01() || !inA_V.read().is_01())? sc_lv<17>(): (sc_biguint<17>(inB_V.read()) + sc_biguint<17>(inA_V.read()));
}

void simpleALU::thread_ap_done() {
    ap_done = ap_start.read();
}

void simpleALU::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void simpleALU::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void simpleALU::thread_ap_return() {
    ap_return = (!op_V.read()[0].is_01())? sc_lv<17>(): ((op_V.read()[0].to_bool())? agg_result_V_assign_fu_42_p2.read(): tmp_1_fu_36_p2.read());
}

void simpleALU::thread_tmp_1_fu_36_p2() {
    tmp_1_fu_36_p2 = (!inA_V.read().is_01() || !inB_V.read().is_01())? sc_lv<17>(): (sc_biguint<17>(inA_V.read()) - sc_biguint<17>(inB_V.read()));
}

void simpleALU::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inA_V\" :  \"" << inA_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inB_V\" :  \"" << inB_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"op_V\" :  \"" << op_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

