// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern ap_fixed<16, 5, (ap_q_mode) 5, (ap_o_mode)3, 0> AESL_WRAP_distPoints_fix (
ap_fixed<16, 5, (ap_q_mode) 5, (ap_o_mode)3, 0> x1,
ap_fixed<16, 5, (ap_q_mode) 5, (ap_o_mode)3, 0> y1,
ap_fixed<16, 5, (ap_q_mode) 5, (ap_o_mode)3, 0> x2,
ap_fixed<16, 5, (ap_q_mode) 5, (ap_o_mode)3, 0> y2);
