// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of address
//        bit 31~0 - address[31:0] (Read/Write)
// 0x14 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSETMEM_AXILITES_ADDR_ADDRESS_DATA 0x10
#define XSETMEM_AXILITES_BITS_ADDRESS_DATA 32

// CRTL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of value_r
//        bit 7~0 - value_r[7:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of size
//        bit 31~0 - size[31:0] (Read/Write)
// 0x1c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSETMEM_CRTL_BUS_ADDR_VALUE_R_DATA 0x10
#define XSETMEM_CRTL_BUS_BITS_VALUE_R_DATA 8
#define XSETMEM_CRTL_BUS_ADDR_SIZE_DATA    0x18
#define XSETMEM_CRTL_BUS_BITS_SIZE_DATA    32

