// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsetmem.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSetmem_CfgInitialize(XSetmem *InstancePtr, XSetmem_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSetmem_Set_address(XSetmem *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSetmem_WriteReg(InstancePtr->Axilites_BaseAddress, XSETMEM_AXILITES_ADDR_ADDRESS_DATA, Data);
}

u32 XSetmem_Get_address(XSetmem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSetmem_ReadReg(InstancePtr->Axilites_BaseAddress, XSETMEM_AXILITES_ADDR_ADDRESS_DATA);
    return Data;
}

void XSetmem_Set_value_r(XSetmem *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSetmem_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSETMEM_CRTL_BUS_ADDR_VALUE_R_DATA, Data);
}

u32 XSetmem_Get_value_r(XSetmem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSetmem_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSETMEM_CRTL_BUS_ADDR_VALUE_R_DATA);
    return Data;
}

void XSetmem_Set_size(XSetmem *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSetmem_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XSETMEM_CRTL_BUS_ADDR_SIZE_DATA, Data);
}

u32 XSetmem_Get_size(XSetmem *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSetmem_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XSETMEM_CRTL_BUS_ADDR_SIZE_DATA);
    return Data;
}

