// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XNORMALIZE_H
#define XNORMALIZE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xnormalize_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XNormalize_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XNormalize;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XNormalize_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XNormalize_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XNormalize_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XNormalize_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XNormalize_Initialize(XNormalize *InstancePtr, u16 DeviceId);
XNormalize_Config* XNormalize_LookupConfig(u16 DeviceId);
int XNormalize_CfgInitialize(XNormalize *InstancePtr, XNormalize_Config *ConfigPtr);
#else
int XNormalize_Initialize(XNormalize *InstancePtr, const char* InstanceName);
int XNormalize_Release(XNormalize *InstancePtr);
#endif

void XNormalize_Start(XNormalize *InstancePtr);
u32 XNormalize_IsDone(XNormalize *InstancePtr);
u32 XNormalize_IsIdle(XNormalize *InstancePtr);
u32 XNormalize_IsReady(XNormalize *InstancePtr);
void XNormalize_EnableAutoRestart(XNormalize *InstancePtr);
void XNormalize_DisableAutoRestart(XNormalize *InstancePtr);

void XNormalize_Set_xMin(XNormalize *InstancePtr, u32 Data);
u32 XNormalize_Get_xMin(XNormalize *InstancePtr);
void XNormalize_Set_xMax(XNormalize *InstancePtr, u32 Data);
u32 XNormalize_Get_xMax(XNormalize *InstancePtr);

void XNormalize_InterruptGlobalEnable(XNormalize *InstancePtr);
void XNormalize_InterruptGlobalDisable(XNormalize *InstancePtr);
void XNormalize_InterruptEnable(XNormalize *InstancePtr, u32 Mask);
void XNormalize_InterruptDisable(XNormalize *InstancePtr, u32 Mask);
void XNormalize_InterruptClear(XNormalize *InstancePtr, u32 Mask);
u32 XNormalize_InterruptGetEnabled(XNormalize *InstancePtr);
u32 XNormalize_InterruptGetStatus(XNormalize *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
