-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity divide is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    N : IN STD_LOGIC_VECTOR (7 downto 0);
    D : IN STD_LOGIC_VECTOR (7 downto 0);
    Q : OUT STD_LOGIC_VECTOR (7 downto 0);
    Q_ap_vld : OUT STD_LOGIC;
    R : OUT STD_LOGIC_VECTOR (7 downto 0);
    R_ap_vld : OUT STD_LOGIC );
end;


architecture behav of divide is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "divide,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.462100,HLS_SYN_LAT=9,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=33,HLS_SYN_LUT=194,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal tmp_fu_86_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_202 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_224 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_1_fu_106_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_159_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_reg_228 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_1_fu_185_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_reg_74 : STD_LOGIC_VECTOR (3 downto 0);
    signal R_load_fu_38 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_142_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal Q_load_fu_42 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_164_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_cast_fu_102_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_117_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_123_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal iBitN_fu_128_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_138_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_2_fu_134_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    Q_load_fu_42_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_s_fu_151_p2 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                Q_load_fu_42 <= tmp_7_fu_164_p2;
            elsif (((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                Q_load_fu_42 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    R_load_fu_38_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_224 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                R_load_fu_38 <= tmp_6_reg_228;
            elsif (((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_s_fu_151_p2 = ap_const_lv1_1) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                R_load_fu_38 <= tmp_9_fu_142_p3;
            elsif (((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                R_load_fu_38 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    i_reg_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_74 <= i_1_fu_185_p2;
            elsif (((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_74 <= ap_const_lv4_7;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_s_fu_151_p2 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_6_reg_228 <= tmp_6_fu_159_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                tmp_reg_202 <= tmp_fu_86_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_s_reg_224 <= tmp_s_fu_151_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_reg_202, ap_CS_fsm_state2, tmp_1_fu_106_p3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((tmp_1_fu_106_p3 = ap_const_lv1_1) or (tmp_reg_202 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    Q_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_fu_86_p2, tmp_reg_202, tmp_s_fu_151_p2, ap_CS_fsm_state2, tmp_1_fu_106_p3, tmp_7_fu_164_p2)
    begin
        if (((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_s_fu_151_p2 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            Q <= tmp_7_fu_164_p2;
        elsif (((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Q <= ap_const_lv8_0;
        else 
            Q <= "XXXXXXXX";
        end if; 
    end process;


    Q_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_fu_86_p2, tmp_reg_202, tmp_s_fu_151_p2, ap_CS_fsm_state2, tmp_1_fu_106_p3)
    begin
        if ((((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_s_fu_151_p2 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            Q_ap_vld <= ap_const_logic_1;
        else 
            Q_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    R_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_fu_86_p2, tmp_reg_202, tmp_s_reg_224, ap_CS_fsm_state2, tmp_1_fu_106_p3, tmp_6_reg_228, ap_CS_fsm_state3, tmp_9_fu_142_p3)
    begin
        if (((tmp_s_reg_224 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            R <= tmp_6_reg_228;
        elsif (((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            R <= tmp_9_fu_142_p3;
        elsif (((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R <= ap_const_lv8_0;
        else 
            R <= "XXXXXXXX";
        end if; 
    end process;


    R_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_fu_86_p2, tmp_reg_202, tmp_s_reg_224, ap_CS_fsm_state2, tmp_1_fu_106_p3, ap_CS_fsm_state3)
    begin
        if ((((tmp_s_reg_224 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)) or ((tmp_1_fu_106_p3 = ap_const_lv1_0) and (tmp_reg_202 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_1) and (tmp_fu_86_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            R_ap_vld <= ap_const_logic_1;
        else 
            R_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(tmp_reg_202, ap_CS_fsm_state2, tmp_1_fu_106_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((tmp_1_fu_106_p3 = ap_const_lv1_1) or (tmp_reg_202 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(tmp_reg_202, ap_CS_fsm_state2, tmp_1_fu_106_p3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((tmp_1_fu_106_p3 = ap_const_lv1_1) or (tmp_reg_202 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    iBitN_fu_128_p2 <= std_logic_vector(shift_right(unsigned(tmp_5_fu_123_p2),to_integer(unsigned('0' & i_cast_fu_102_p1(8-1 downto 0)))));
    i_1_fu_185_p2 <= std_logic_vector(signed(i_reg_74) + signed(ap_const_lv4_F));
        i_cast_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(i_reg_74),8));

    tmp_1_fu_106_p3 <= i_reg_74(3 downto 3);
    tmp_2_fu_134_p1 <= iBitN_fu_128_p2(1 - 1 downto 0);
    tmp_3_fu_138_p1 <= R_load_fu_38(7 - 1 downto 0);
    tmp_4_fu_117_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv8_1),to_integer(unsigned('0' & i_cast_fu_102_p1(8-1 downto 0)))));
    tmp_5_fu_123_p2 <= (tmp_4_fu_117_p2 and N);
    tmp_6_fu_159_p2 <= std_logic_vector(unsigned(tmp_9_fu_142_p3) - unsigned(D));
    tmp_7_fu_164_p2 <= (tmp_4_fu_117_p2 or Q_load_fu_42);
    tmp_9_fu_142_p3 <= (tmp_3_fu_138_p1 & tmp_2_fu_134_p1);
    tmp_fu_86_p2 <= "1" when (D = ap_const_lv8_0) else "0";
    tmp_s_fu_151_p2 <= "1" when (unsigned(tmp_9_fu_142_p3) < unsigned(D)) else "0";
end behav;
