// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmathfunction.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMathfunction_CfgInitialize(XMathfunction *InstancePtr, XMathfunction_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMathfunction_Start(XMathfunction *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMathfunction_IsDone(XMathfunction *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMathfunction_IsIdle(XMathfunction *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMathfunction_IsReady(XMathfunction *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMathfunction_EnableAutoRestart(XMathfunction *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMathfunction_DisableAutoRestart(XMathfunction *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XMathfunction_Set_y(XMathfunction *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_Y_DATA, Data);
}

u32 XMathfunction_Get_y(XMathfunction *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_Y_DATA);
    return Data;
}

void XMathfunction_InterruptGlobalEnable(XMathfunction *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_GIE, 1);
}

void XMathfunction_InterruptGlobalDisable(XMathfunction *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_GIE, 0);
}

void XMathfunction_InterruptEnable(XMathfunction *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_IER);
    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XMathfunction_InterruptDisable(XMathfunction *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_IER);
    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XMathfunction_InterruptClear(XMathfunction *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMathfunction_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XMathfunction_InterruptGetEnabled(XMathfunction *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_IER);
}

u32 XMathfunction_InterruptGetStatus(XMathfunction *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMathfunction_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XMATHFUNCTION_CRTL_BUS_ADDR_ISR);
}

