// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMATHFUNCTION_H
#define XMATHFUNCTION_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmathfunction_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Crtl_bus_BaseAddress;
} XMathfunction_Config;
#endif

typedef struct {
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XMathfunction;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMathfunction_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMathfunction_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMathfunction_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMathfunction_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMathfunction_Initialize(XMathfunction *InstancePtr, u16 DeviceId);
XMathfunction_Config* XMathfunction_LookupConfig(u16 DeviceId);
int XMathfunction_CfgInitialize(XMathfunction *InstancePtr, XMathfunction_Config *ConfigPtr);
#else
int XMathfunction_Initialize(XMathfunction *InstancePtr, const char* InstanceName);
int XMathfunction_Release(XMathfunction *InstancePtr);
#endif

void XMathfunction_Start(XMathfunction *InstancePtr);
u32 XMathfunction_IsDone(XMathfunction *InstancePtr);
u32 XMathfunction_IsIdle(XMathfunction *InstancePtr);
u32 XMathfunction_IsReady(XMathfunction *InstancePtr);
void XMathfunction_EnableAutoRestart(XMathfunction *InstancePtr);
void XMathfunction_DisableAutoRestart(XMathfunction *InstancePtr);

void XMathfunction_Set_y(XMathfunction *InstancePtr, u32 Data);
u32 XMathfunction_Get_y(XMathfunction *InstancePtr);

void XMathfunction_InterruptGlobalEnable(XMathfunction *InstancePtr);
void XMathfunction_InterruptGlobalDisable(XMathfunction *InstancePtr);
void XMathfunction_InterruptEnable(XMathfunction *InstancePtr, u32 Mask);
void XMathfunction_InterruptDisable(XMathfunction *InstancePtr, u32 Mask);
void XMathfunction_InterruptClear(XMathfunction *InstancePtr, u32 Mask);
u32 XMathfunction_InterruptGetEnabled(XMathfunction *InstancePtr);
u32 XMathfunction_InterruptGetStatus(XMathfunction *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
