// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "inA_V"
#define AUTOTB_TVIN_inA_V  "../tv/cdatafile/c.simpleALU.autotvin_inA_V.dat"
// wrapc file define: "inB_V"
#define AUTOTB_TVIN_inB_V  "../tv/cdatafile/c.simpleALU.autotvin_inB_V.dat"
// wrapc file define: "op_V"
#define AUTOTB_TVIN_op_V  "../tv/cdatafile/c.simpleALU.autotvin_op_V.dat"
// wrapc file define: "ap_return"
#define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.simpleALU.autotvout_ap_return.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "ap_return"
#define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.simpleALU.autotvout_ap_return.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			inA_V_depth = 0;
			inB_V_depth = 0;
			op_V_depth = 0;
			ap_return_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{inA_V " << inA_V_depth << "}\n";
			total_list << "{inB_V " << inB_V_depth << "}\n";
			total_list << "{op_V " << op_V_depth << "}\n";
			total_list << "{ap_return " << ap_return_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int inA_V_depth;
		int inB_V_depth;
		int op_V_depth;
		int ap_return_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern ap_uint<17> simpleALU (
ap_uint<17> inA,
ap_uint<17> inB,
ap_uint<1> op);

ap_uint<17> AESL_WRAP_simpleALU (
ap_uint<17> inA,
ap_uint<17> inB,
ap_uint<1> op)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		ap_uint<17> AESL_return;

		// output port post check: "ap_return"
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data

			sc_bv<17> ap_return_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ap_return_pc_buffer = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ap_return
				{
					// bitslice(16, 0)
					// {
						// celement: agg.result.V(16, 0)
						// {
							sc_lv<17> agg_result_V_lv0_0_0_0;
						// }
					// }

					// bitslice(16, 0)
					{
						// celement: agg.result.V(16, 0)
						{
							// carray: (0) => (0) @ (0)
							{
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									agg_result_V_lv0_0_0_0.range(16, 0) = sc_bv<17>(ap_return_pc_buffer.range(16, 0));
								}
							}
						}
					}

					// bitslice(16, 0)
					{
						// celement: agg.result.V(16, 0)
						{
							// carray: (0) => (0) @ (0)
							{
								// sub                    : 
								// ori_name               : AESL_return
								// sub_1st_elem           : 
								// ori_name_1st_elem      : AESL_return
								// output_left_conversion : AESL_return
								// output_type_conversion : (agg_result_V_lv0_0_0_0).to_string(SC_BIN).c_str()
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									AESL_return = (agg_result_V_lv0_0_0_0).to_string(SC_BIN).c_str();
								}
							}
						}
					}
				}
			}
		}

		AESL_transaction_pc++;

		return AESL_return;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "inA_V"
		char* tvin_inA_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_inA_V);

		// "inB_V"
		char* tvin_inB_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_inB_V);

		// "op_V"
		char* tvin_op_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_op_V);

		// "ap_return"
		char* tvout_ap_return = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ap_return);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_inA_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_inA_V, tvin_inA_V);

		sc_bv<17> inA_V_tvin_wrapc_buffer;

		// RTL Name: inA_V
		{
			// bitslice(16, 0)
			{
				// celement: inA.V(16, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : inA
						// sub_1st_elem          : 
						// ori_name_1st_elem     : inA
						// regulate_c_name       : inA_V
						// input_type_conversion : (inA).to_string(2).c_str()
						if (&(inA) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<17> inA_V_tmp_mem;
							inA_V_tmp_mem = (inA).to_string(2).c_str();
							inA_V_tvin_wrapc_buffer.range(16, 0) = inA_V_tmp_mem.range(16, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_inA_V, "%s\n", (inA_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_inA_V, tvin_inA_V);
		}

		tcl_file.set_num(1, &tcl_file.inA_V_depth);
		sprintf(tvin_inA_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_inA_V, tvin_inA_V);

		// [[transaction]]
		sprintf(tvin_inB_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_inB_V, tvin_inB_V);

		sc_bv<17> inB_V_tvin_wrapc_buffer;

		// RTL Name: inB_V
		{
			// bitslice(16, 0)
			{
				// celement: inB.V(16, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : inB
						// sub_1st_elem          : 
						// ori_name_1st_elem     : inB
						// regulate_c_name       : inB_V
						// input_type_conversion : (inB).to_string(2).c_str()
						if (&(inB) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<17> inB_V_tmp_mem;
							inB_V_tmp_mem = (inB).to_string(2).c_str();
							inB_V_tvin_wrapc_buffer.range(16, 0) = inB_V_tmp_mem.range(16, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_inB_V, "%s\n", (inB_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_inB_V, tvin_inB_V);
		}

		tcl_file.set_num(1, &tcl_file.inB_V_depth);
		sprintf(tvin_inB_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_inB_V, tvin_inB_V);

		// [[transaction]]
		sprintf(tvin_op_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_op_V, tvin_op_V);

		sc_bv<1> op_V_tvin_wrapc_buffer;

		// RTL Name: op_V
		{
			// bitslice(0, 0)
			{
				// celement: op.V(0, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : op
						// sub_1st_elem          : 
						// ori_name_1st_elem     : op
						// regulate_c_name       : op_V
						// input_type_conversion : (op).to_string(2).c_str()
						if (&(op) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<1> op_V_tmp_mem;
							op_V_tmp_mem = (op).to_string(2).c_str();
							op_V_tvin_wrapc_buffer.range(0, 0) = op_V_tmp_mem.range(0, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_op_V, "%s\n", (op_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_op_V, tvin_op_V);
		}

		tcl_file.set_num(1, &tcl_file.op_V_depth);
		sprintf(tvin_op_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_op_V, tvin_op_V);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		ap_uint<17> AESL_return = simpleALU(inA, inB, op);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		sc_bv<17> ap_return_tvout_wrapc_buffer;

		// RTL Name: ap_return
		{
			// bitslice(16, 0)
			{
				// celement: agg.result.V(16, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : AESL_return
						// sub_1st_elem          : 
						// ori_name_1st_elem     : AESL_return
						// regulate_c_name       : agg_result_V
						// input_type_conversion : (AESL_return).to_string(2).c_str()
						if (&(AESL_return) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<17> agg_result_V_tmp_mem;
							agg_result_V_tmp_mem = (AESL_return).to_string(2).c_str();
							ap_return_tvout_wrapc_buffer.range(16, 0) = agg_result_V_tmp_mem.range(16, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);
		}

		tcl_file.set_num(1, &tcl_file.ap_return_depth);
		sprintf(tvout_ap_return, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "inA_V"
		delete [] tvin_inA_V;
		// release memory allocation: "inB_V"
		delete [] tvin_inB_V;
		// release memory allocation: "op_V"
		delete [] tvin_op_V;
		// release memory allocation: "ap_return"
		delete [] tvout_ap_return;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

		return AESL_return;
	}
}

