// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "ximageprocess.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XImageprocess_CfgInitialize(XImageprocess *InstancePtr, XImageprocess_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Kernel_bus_BaseAddress = ConfigPtr->Kernel_bus_BaseAddress;
    InstancePtr->Crtl_bus_BaseAddress = ConfigPtr->Crtl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XImageprocess_Start(XImageprocess *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL) & 0x80;
    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XImageprocess_IsDone(XImageprocess *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XImageprocess_IsIdle(XImageprocess *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XImageprocess_IsReady(XImageprocess *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XImageprocess_EnableAutoRestart(XImageprocess *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL, 0x80);
}

void XImageprocess_DisableAutoRestart(XImageprocess *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_AP_CTRL, 0);
}

void XImageprocess_Set_operation(XImageprocess *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_OPERATION_DATA, Data);
}

u32 XImageprocess_Get_operation(XImageprocess *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_OPERATION_DATA);
    return Data;
}

u32 XImageprocess_Get_kernel_BaseAddress(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE);
}

u32 XImageprocess_Get_kernel_HighAddress(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Kernel_bus_BaseAddress + XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_HIGH);
}

u32 XImageprocess_Get_kernel_TotalBytes(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_HIGH - XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + 1);
}

u32 XImageprocess_Get_kernel_BitWidth(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIMAGEPROCESS_KERNEL_BUS_WIDTH_KERNEL;
}

u32 XImageprocess_Get_kernel_Depth(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIMAGEPROCESS_KERNEL_BUS_DEPTH_KERNEL;
}

u32 XImageprocess_Write_kernel_Words(XImageprocess *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_HIGH - XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Kernel_bus_BaseAddress + XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XImageprocess_Read_kernel_Words(XImageprocess *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_HIGH - XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Kernel_bus_BaseAddress + XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + (offset + i)*4);
    }
    return length;
}

u32 XImageprocess_Write_kernel_Bytes(XImageprocess *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_HIGH - XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Kernel_bus_BaseAddress + XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XImageprocess_Read_kernel_Bytes(XImageprocess *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_HIGH - XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Kernel_bus_BaseAddress + XIMAGEPROCESS_KERNEL_BUS_ADDR_KERNEL_BASE + offset + i);
    }
    return length;
}

void XImageprocess_InterruptGlobalEnable(XImageprocess *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_GIE, 1);
}

void XImageprocess_InterruptGlobalDisable(XImageprocess *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_GIE, 0);
}

void XImageprocess_InterruptEnable(XImageprocess *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_IER);
    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_IER, Register | Mask);
}

void XImageprocess_InterruptDisable(XImageprocess *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_IER);
    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_IER, Register & (~Mask));
}

void XImageprocess_InterruptClear(XImageprocess *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XImageprocess_WriteReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_ISR, Mask);
}

u32 XImageprocess_InterruptGetEnabled(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_IER);
}

u32 XImageprocess_InterruptGetStatus(XImageprocess *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XImageprocess_ReadReg(InstancePtr->Crtl_bus_BaseAddress, XIMAGEPROCESS_CRTL_BUS_ADDR_ISR);
}

