// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "mathFunction.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic mathFunction::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic mathFunction::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> mathFunction::ap_ST_fsm_state1 = "1";
const sc_lv<32> mathFunction::ap_ST_fsm_state2 = "10";
const sc_lv<32> mathFunction::ap_ST_fsm_state3 = "100";
const sc_lv<32> mathFunction::ap_ST_fsm_state4 = "1000";
const sc_lv<32> mathFunction::ap_ST_fsm_state5 = "10000";
const sc_lv<32> mathFunction::ap_ST_fsm_state6 = "100000";
const sc_lv<32> mathFunction::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<32> mathFunction::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<32> mathFunction::ap_const_lv32_0 = "00000000000000000000000000000000";
const int mathFunction::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> mathFunction::ap_const_lv32_1 = "1";
const sc_lv<32> mathFunction::ap_const_lv32_5 = "101";
const sc_lv<32> mathFunction::ap_const_lv32_6 = "110";
const sc_lv<32> mathFunction::ap_const_lv32_7 = "111";
const sc_lv<32> mathFunction::ap_const_lv32_8 = "1000";
const sc_lv<32> mathFunction::ap_const_lv32_9 = "1001";
const sc_lv<32> mathFunction::ap_const_lv32_D = "1101";
const sc_lv<1> mathFunction::ap_const_lv1_0 = "0";
const sc_lv<32> mathFunction::ap_const_lv32_E = "1110";
const sc_lv<32> mathFunction::ap_const_lv32_F = "1111";
const sc_lv<32> mathFunction::ap_const_lv32_10 = "10000";
const sc_lv<32> mathFunction::ap_const_lv32_11 = "10001";
const sc_lv<32> mathFunction::ap_const_lv32_12 = "10010";
const sc_lv<32> mathFunction::ap_const_lv32_13 = "10011";
const sc_lv<32> mathFunction::ap_const_lv32_14 = "10100";
const sc_lv<32> mathFunction::ap_const_lv32_15 = "10101";
const sc_lv<32> mathFunction::ap_const_lv32_16 = "10110";
const sc_lv<32> mathFunction::ap_const_lv32_1A = "11010";
const sc_lv<32> mathFunction::ap_const_lv32_1E = "11110";
const sc_lv<7> mathFunction::ap_const_lv7_0 = "0000000";
const sc_lv<32> mathFunction::ap_const_lv32_1F = "11111";
const sc_lv<32> mathFunction::ap_const_lv32_2 = "10";
const sc_lv<4> mathFunction::ap_const_lv4_0 = "0000";
const sc_lv<4> mathFunction::ap_const_lv4_F = "1111";
const sc_lv<32> mathFunction::ap_const_lv32_3F000000 = "111111000000000000000000000000";
const sc_lv<32> mathFunction::ap_const_lv32_1B = "11011";
const sc_lv<32> mathFunction::ap_const_lv32_A = "1010";
const sc_lv<7> mathFunction::ap_const_lv7_64 = "1100100";
const sc_lv<7> mathFunction::ap_const_lv7_1 = "1";
const sc_lv<32> mathFunction::ap_const_lv32_17 = "10111";
const sc_lv<8> mathFunction::ap_const_lv8_7E = "1111110";
const sc_lv<8> mathFunction::ap_const_lv8_C2 = "11000010";
const sc_lv<8> mathFunction::ap_const_lv8_3F = "111111";
const sc_lv<32> mathFunction::ap_const_lv32_4 = "100";
const sc_lv<32> mathFunction::ap_const_lv32_63 = "1100011";
const sc_lv<1> mathFunction::ap_const_lv1_1 = "1";
const sc_lv<23> mathFunction::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> mathFunction::ap_const_lv32_4C = "1001100";
const sc_lv<32> mathFunction::ap_const_lv32_4D = "1001101";
const sc_lv<32> mathFunction::ap_const_lv32_4F = "1001111";
const sc_lv<3> mathFunction::ap_const_lv3_0 = "000";
const sc_lv<58> mathFunction::ap_const_lv58_0 = "0000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> mathFunction::ap_const_lv32_1D = "11101";
const sc_lv<32> mathFunction::ap_const_lv32_39 = "111001";
const sc_lv<2> mathFunction::ap_const_lv2_3 = "11";
const sc_lv<8> mathFunction::ap_const_lv8_83 = "10000011";
const sc_lv<8> mathFunction::ap_const_lv8_0 = "00000000";
const sc_lv<9> mathFunction::ap_const_lv9_0 = "000000000";
const sc_lv<8> mathFunction::ap_const_lv8_FF = "11111111";
const sc_lv<32> mathFunction::ap_const_lv32_1C = "11100";
const sc_lv<32> mathFunction::ap_const_lv32_2C = "101100";
const sc_lv<29> mathFunction::ap_const_lv29_1FFFFFFF = "11111111111111111111111111111";
const sc_lv<23> mathFunction::ap_const_lv23_7FFFFF = "11111111111111111111111";
const sc_lv<32> mathFunction::ap_const_lv32_B = "1011";
const sc_lv<32> mathFunction::ap_const_lv32_C = "1100";
const bool mathFunction::ap_const_boolean_1 = true;

mathFunction::mathFunction(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ref_4oPi_table_100_V_U = new mathFunction_ref_bkb("ref_4oPi_table_100_V_U");
    ref_4oPi_table_100_V_U->clk(ap_clk);
    ref_4oPi_table_100_V_U->reset(ap_rst_n_inv);
    ref_4oPi_table_100_V_U->address0(ref_4oPi_table_100_V_address0);
    ref_4oPi_table_100_V_U->ce0(ref_4oPi_table_100_V_ce0);
    ref_4oPi_table_100_V_U->q0(ref_4oPi_table_100_V_q0);
    second_order_float_2_U = new mathFunction_secocud("second_order_float_2_U");
    second_order_float_2_U->clk(ap_clk);
    second_order_float_2_U->reset(ap_rst_n_inv);
    second_order_float_2_U->address0(second_order_float_2_address0);
    second_order_float_2_U->ce0(second_order_float_2_ce0);
    second_order_float_2_U->q0(second_order_float_2_q0);
    second_order_float_3_U = new mathFunction_secodEe("second_order_float_3_U");
    second_order_float_3_U->clk(ap_clk);
    second_order_float_3_U->reset(ap_rst_n_inv);
    second_order_float_3_U->address0(second_order_float_3_address0);
    second_order_float_3_U->ce0(second_order_float_3_ce0);
    second_order_float_3_U->q0(second_order_float_3_q0);
    second_order_float_s_U = new mathFunction_secoeOg("second_order_float_s_U");
    second_order_float_s_U->clk(ap_clk);
    second_order_float_s_U->reset(ap_rst_n_inv);
    second_order_float_s_U->address0(second_order_float_s_address0);
    second_order_float_s_U->ce0(second_order_float_s_ce0);
    second_order_float_s_U->q0(second_order_float_s_q0);
    mathFunction_CRTL_BUS_s_axi_U = new mathFunction_CRTL_BUS_s_axi<C_S_AXI_CRTL_BUS_ADDR_WIDTH,C_S_AXI_CRTL_BUS_DATA_WIDTH>("mathFunction_CRTL_BUS_s_axi_U");
    mathFunction_CRTL_BUS_s_axi_U->AWVALID(s_axi_CRTL_BUS_AWVALID);
    mathFunction_CRTL_BUS_s_axi_U->AWREADY(s_axi_CRTL_BUS_AWREADY);
    mathFunction_CRTL_BUS_s_axi_U->AWADDR(s_axi_CRTL_BUS_AWADDR);
    mathFunction_CRTL_BUS_s_axi_U->WVALID(s_axi_CRTL_BUS_WVALID);
    mathFunction_CRTL_BUS_s_axi_U->WREADY(s_axi_CRTL_BUS_WREADY);
    mathFunction_CRTL_BUS_s_axi_U->WDATA(s_axi_CRTL_BUS_WDATA);
    mathFunction_CRTL_BUS_s_axi_U->WSTRB(s_axi_CRTL_BUS_WSTRB);
    mathFunction_CRTL_BUS_s_axi_U->ARVALID(s_axi_CRTL_BUS_ARVALID);
    mathFunction_CRTL_BUS_s_axi_U->ARREADY(s_axi_CRTL_BUS_ARREADY);
    mathFunction_CRTL_BUS_s_axi_U->ARADDR(s_axi_CRTL_BUS_ARADDR);
    mathFunction_CRTL_BUS_s_axi_U->RVALID(s_axi_CRTL_BUS_RVALID);
    mathFunction_CRTL_BUS_s_axi_U->RREADY(s_axi_CRTL_BUS_RREADY);
    mathFunction_CRTL_BUS_s_axi_U->RDATA(s_axi_CRTL_BUS_RDATA);
    mathFunction_CRTL_BUS_s_axi_U->RRESP(s_axi_CRTL_BUS_RRESP);
    mathFunction_CRTL_BUS_s_axi_U->BVALID(s_axi_CRTL_BUS_BVALID);
    mathFunction_CRTL_BUS_s_axi_U->BREADY(s_axi_CRTL_BUS_BREADY);
    mathFunction_CRTL_BUS_s_axi_U->BRESP(s_axi_CRTL_BUS_BRESP);
    mathFunction_CRTL_BUS_s_axi_U->ACLK(ap_clk);
    mathFunction_CRTL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    mathFunction_CRTL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    mathFunction_CRTL_BUS_s_axi_U->ap_start(ap_start);
    mathFunction_CRTL_BUS_s_axi_U->interrupt(interrupt);
    mathFunction_CRTL_BUS_s_axi_U->ap_ready(ap_ready);
    mathFunction_CRTL_BUS_s_axi_U->ap_done(ap_done);
    mathFunction_CRTL_BUS_s_axi_U->ap_idle(ap_idle);
    mathFunction_CRTL_BUS_s_axi_U->y(y);
    grp_scaled_fixed2ieee_fu_280 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_280");
    grp_scaled_fixed2ieee_fu_280->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_280->ap_rst(ap_rst_n_inv);
    grp_scaled_fixed2ieee_fu_280->ap_start(grp_scaled_fixed2ieee_fu_280_ap_start);
    grp_scaled_fixed2ieee_fu_280->ap_done(grp_scaled_fixed2ieee_fu_280_ap_done);
    grp_scaled_fixed2ieee_fu_280->ap_idle(grp_scaled_fixed2ieee_fu_280_ap_idle);
    grp_scaled_fixed2ieee_fu_280->ap_ready(grp_scaled_fixed2ieee_fu_280_ap_ready);
    grp_scaled_fixed2ieee_fu_280->in_V(result_V_reg_1259);
    grp_scaled_fixed2ieee_fu_280->prescale(r_V_1_reg_1264);
    grp_scaled_fixed2ieee_fu_280->ap_return(grp_scaled_fixed2ieee_fu_280_ap_return);
    mathFunction_faddfYi_U3 = new mathFunction_faddfYi<1,5,32,32,32>("mathFunction_faddfYi_U3");
    mathFunction_faddfYi_U3->clk(ap_clk);
    mathFunction_faddfYi_U3->reset(ap_rst_n_inv);
    mathFunction_faddfYi_U3->din0(grp_fu_286_p0);
    mathFunction_faddfYi_U3->din1(tmp_i_reg_1289);
    mathFunction_faddfYi_U3->ce(ap_var_for_const0);
    mathFunction_faddfYi_U3->dout(grp_fu_286_p2);
    mathFunction_fmulg8j_U4 = new mathFunction_fmulg8j<1,4,32,32,32>("mathFunction_fmulg8j_U4");
    mathFunction_fmulg8j_U4->clk(ap_clk);
    mathFunction_fmulg8j_U4->reset(ap_rst_n_inv);
    mathFunction_fmulg8j_U4->din0(tmp_9_reg_1299);
    mathFunction_fmulg8j_U4->din1(ap_var_for_const1);
    mathFunction_fmulg8j_U4->ce(ap_var_for_const0);
    mathFunction_fmulg8j_U4->dout(grp_fu_290_p2);
    mathFunction_fsqrhbi_U5 = new mathFunction_fsqrhbi<1,12,32,32,32>("mathFunction_fsqrhbi_U5");
    mathFunction_fsqrhbi_U5->clk(ap_clk);
    mathFunction_fsqrhbi_U5->reset(ap_rst_n_inv);
    mathFunction_fsqrhbi_U5->din0(ap_var_for_const2);
    mathFunction_fsqrhbi_U5->din1(x_assign_reg_1118);
    mathFunction_fsqrhbi_U5->ce(grp_fu_295_ce);
    mathFunction_fsqrhbi_U5->dout(grp_fu_295_p2);
    mathFunction_fexpibs_U6 = new mathFunction_fexpibs<1,9,32,32,32>("mathFunction_fexpibs_U6");
    mathFunction_fexpibs_U6->clk(ap_clk);
    mathFunction_fexpibs_U6->reset(ap_rst_n_inv);
    mathFunction_fexpibs_U6->din0(ap_var_for_const2);
    mathFunction_fexpibs_U6->din1(y_read_reg_1034);
    mathFunction_fexpibs_U6->ce(ap_var_for_const0);
    mathFunction_fexpibs_U6->dout(grp_fu_300_p2);
    mathFunction_mul_jbC_U7 = new mathFunction_mul_jbC<1,5,80,24,104>("mathFunction_mul_jbC_U7");
    mathFunction_mul_jbC_U7->clk(ap_clk);
    mathFunction_mul_jbC_U7->reset(ap_rst_n_inv);
    mathFunction_mul_jbC_U7->din0(grp_fu_419_p0);
    mathFunction_mul_jbC_U7->din1(grp_fu_419_p1);
    mathFunction_mul_jbC_U7->ce(ap_var_for_const0);
    mathFunction_mul_jbC_U7->dout(grp_fu_419_p2);
    mathFunction_mux_kbM_U8 = new mathFunction_mux_kbM<1,1,1,1,1,1,1,1,1,1,3,1>("mathFunction_mux_kbM_U8");
    mathFunction_mux_kbM_U8->din0(ap_var_for_const3);
    mathFunction_mux_kbM_U8->din1(ap_var_for_const4);
    mathFunction_mux_kbM_U8->din2(ap_var_for_const4);
    mathFunction_mux_kbM_U8->din3(ap_var_for_const3);
    mathFunction_mux_kbM_U8->din4(ap_var_for_const3);
    mathFunction_mux_kbM_U8->din5(ap_var_for_const4);
    mathFunction_mux_kbM_U8->din6(ap_var_for_const4);
    mathFunction_mux_kbM_U8->din7(ap_var_for_const3);
    mathFunction_mux_kbM_U8->din8(p_Val2_22_reg_1134);
    mathFunction_mux_kbM_U8->dout(cos_basis_fu_626_p10);
    mathFunction_mux_lbW_U9 = new mathFunction_mux_lbW<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("mathFunction_mux_lbW_U9");
    mathFunction_mux_lbW_U9->din0(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din1(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din2(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din3(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din4(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din5(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din6(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din7(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din8(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din9(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din10(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din11(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din12(ap_var_for_const4);
    mathFunction_mux_lbW_U9->din13(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din14(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din15(ap_var_for_const3);
    mathFunction_mux_lbW_U9->din16(p_Result_30_fu_844_p3);
    mathFunction_mux_lbW_U9->dout(tmp_fu_850_p18);
    mathFunction_mux_lbW_U10 = new mathFunction_mux_lbW<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("mathFunction_mux_lbW_U10");
    mathFunction_mux_lbW_U10->din0(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din1(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din2(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din3(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din4(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din5(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din6(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din7(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din8(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din9(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din10(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din11(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din12(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din13(ap_var_for_const4);
    mathFunction_mux_lbW_U10->din14(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din15(ap_var_for_const3);
    mathFunction_mux_lbW_U10->din16(p_Result_30_fu_844_p3);
    mathFunction_mux_lbW_U10->dout(tmp_12_fu_888_p18);
    mathFunction_mul_mb6_U11 = new mathFunction_mul_mb6<1,1,15,15,30>("mathFunction_mul_mb6_U11");
    mathFunction_mul_mb6_U11->din0(p_Val2_13_fu_1020_p0);
    mathFunction_mul_mb6_U11->din1(p_Val2_13_fu_1020_p1);
    mathFunction_mul_mb6_U11->dout(p_Val2_13_fu_1020_p2);
    mathFunction_mul_ncg_U12 = new mathFunction_mul_ncg<1,1,15,15,30>("mathFunction_mul_ncg_U12");
    mathFunction_mul_ncg_U12->din0(p_Val2_2_fu_1027_p0);
    mathFunction_mul_ncg_U12->din1(second_order_float_8_reg_1234);
    mathFunction_mul_ncg_U12->dout(p_Val2_2_fu_1027_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Ex_V_fu_553_p2);
    sensitive << ( storemerge_i_i_fu_525_p3 );
    sensitive << ( tmp_16_i_i_fu_550_p1 );

    SC_METHOD(thread_Mx_V_read_assign_fu_751_p3);
    sensitive << ( Mx_V_reg_1151 );
    sensitive << ( cos_basis_reg_1187 );

    SC_METHOD(thread_Mx_zeros_V_fu_516_p1);
    sensitive << ( val_assign_fu_508_p3 );

    SC_METHOD(thread_OP1_V_3_fu_692_p1);
    sensitive << ( tmp_i1_i_reg_1199 );

    SC_METHOD(thread_addr_V_fu_359_p3);
    sensitive << ( closepath_fu_347_p2 );
    sensitive << ( expv_op_i_fu_353_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_305_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_305_p2 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_closepath_fu_347_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( loc_V_fu_333_p4 );

    SC_METHOD(thread_exitcond_fu_305_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_268 );

    SC_METHOD(thread_expv_op_i_fu_353_p2);
    sensitive << ( loc_V_fu_333_p4 );

    SC_METHOD(thread_grp_fu_286_p0);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( p_Result_31_fu_1007_p4 );

    SC_METHOD(thread_grp_fu_295_ce);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( grp_scaled_fixed2ieee_fu_280_ap_done );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_419_p0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_fu_419_p00 );

    SC_METHOD(thread_grp_fu_419_p00);
    sensitive << ( Med_V_reg_1097 );

    SC_METHOD(thread_grp_fu_419_p1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_fu_419_p10 );

    SC_METHOD(thread_grp_fu_419_p10);
    sensitive << ( p_Result_24_fu_405_p3 );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_280_ap_start);
    sensitive << ( grp_scaled_fixed2ieee_fu_280_ap_start_reg );

    SC_METHOD(thread_i_2_fu_311_p2);
    sensitive << ( i_reg_268 );

    SC_METHOD(thread_isNeg_fu_563_p3);
    sensitive << ( Ex_V_fu_553_p2 );

    SC_METHOD(thread_loc_V_1_fu_343_p1);
    sensitive << ( p_Val2_s_fu_322_p1 );

    SC_METHOD(thread_loc_V_2_fu_830_p4);
    sensitive << ( p_Val2_18_fu_818_p1 );

    SC_METHOD(thread_loc_V_3_fu_840_p1);
    sensitive << ( p_Val2_18_fu_818_p1 );

    SC_METHOD(thread_loc_V_fu_333_p4);
    sensitive << ( p_Val2_s_fu_322_p1 );

    SC_METHOD(thread_not_or_cond_i_demorg_fu_955_p2);
    sensitive << ( tmp_14_i_reg_1112 );
    sensitive << ( tmp_13_i_reg_1174 );

    SC_METHOD(thread_not_or_cond_i_fu_959_p2);
    sensitive << ( not_or_cond_i_demorg_fu_955_p2 );

    SC_METHOD(thread_not_tmp_i_fu_937_p2);
    sensitive << ( tmp_15_i_reg_1180 );

    SC_METHOD(thread_or_cond_i_fu_933_p2);
    sensitive << ( tmp_14_i_reg_1112 );
    sensitive << ( tmp_13_i_reg_1174 );

    SC_METHOD(thread_p_Ex_V_ret_i_fu_778_p3);
    sensitive << ( Ex_V_reg_1158 );
    sensitive << ( cos_basis_reg_1187 );

    SC_METHOD(thread_p_Result_1_i_cast_fu_986_p3);
    sensitive << ( not_or_cond_i_fu_959_p2 );

    SC_METHOD(thread_p_Result_24_fu_405_p3);
    sensitive << ( loc_V_1_reg_1075 );

    SC_METHOD(thread_p_Result_25_fu_482_p3);
    sensitive << ( p_Result_i2_i_i_fu_472_p4 );

    SC_METHOD(thread_p_Result_26_fu_490_p4);
    sensitive << ( p_Result_25_fu_482_p3 );

    SC_METHOD(thread_p_Result_27_fu_500_p3);
    sensitive << ( p_Result_26_fu_490_p4 );

    SC_METHOD(thread_p_Result_28_fu_677_p3);
    sensitive << ( sin_basis_fu_671_p2 );
    sensitive << ( p_Result_i_i_fu_647_p4 );

    SC_METHOD(thread_p_Result_29_fu_822_p3);
    sensitive << ( p_Val2_18_fu_818_p1 );

    SC_METHOD(thread_p_Result_30_fu_844_p3);
    sensitive << ( results_sign_V_1_reg_1062 );
    sensitive << ( p_Val2_22_reg_1134 );

    SC_METHOD(thread_p_Result_31_fu_1007_p4);
    sensitive << ( ret_V_4_reg_1279 );
    sensitive << ( ret_V_5_reg_1284 );
    sensitive << ( p_Result_s_fu_1002_p3 );

    SC_METHOD(thread_p_Result_i2_i_i_fu_472_p4);
    sensitive << ( p_Val2_8_fu_465_p3 );

    SC_METHOD(thread_p_Result_i_cast_fu_965_p3);
    sensitive << ( not_or_cond_i_fu_959_p2 );

    SC_METHOD(thread_p_Result_i_fu_947_p3);
    sensitive << ( tmp_16_i_fu_942_p2 );
    sensitive << ( not_tmp_i_fu_937_p2 );
    sensitive << ( p_Result_29_fu_822_p3 );

    SC_METHOD(thread_p_Result_i_i_fu_647_p4);
    sensitive << ( ssdm_int_V_write_ass_fu_619_p3 );

    SC_METHOD(thread_p_Result_s_fu_1002_p3);
    sensitive << ( results_sign_V_1_reg_1062 );
    sensitive << ( or_cond_i_reg_1269 );
    sensitive << ( p_Result_i_reg_1274 );

    SC_METHOD(thread_p_Val2_11_fu_535_p2);
    sensitive << ( p_Val2_8_reg_1140 );
    sensitive << ( tmp_13_i_i_fu_532_p1 );

    SC_METHOD(thread_p_Val2_12_fu_657_p1);
    sensitive << ( ssdm_int_V_write_ass_fu_619_p3 );

    SC_METHOD(thread_p_Val2_13_fu_1020_p0);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( OP1_V_3_fu_692_p1 );

    SC_METHOD(thread_p_Val2_13_fu_1020_p1);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( OP1_V_3_fu_692_p1 );

    SC_METHOD(thread_p_Val2_16_fu_763_p2);
    sensitive << ( tmp_33_i_i_fu_757_p1 );
    sensitive << ( tmp_34_i_i_fu_760_p1 );

    SC_METHOD(thread_p_Val2_17_fu_790_p0);
    sensitive << ( r_V_reg_1254 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_p_Val2_17_fu_790_p1);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( p_Val2_17_fu_790_p10 );

    SC_METHOD(thread_p_Val2_17_fu_790_p10);
    sensitive << ( Mx_V_read_assign_reg_1249 );

    SC_METHOD(thread_p_Val2_17_fu_790_p2);
    sensitive << ( p_Val2_17_fu_790_p0 );
    sensitive << ( p_Val2_17_fu_790_p1 );

    SC_METHOD(thread_p_Val2_18_fu_818_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_280_ap_return );

    SC_METHOD(thread_p_Val2_1_fu_720_p0);
    sensitive << ( second_order_float_6_reg_1229 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_p_Val2_1_fu_720_p1);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( p_Val2_1_fu_720_p10 );

    SC_METHOD(thread_p_Val2_1_fu_720_p10);
    sensitive << ( p_Val2_12_reg_1194 );

    SC_METHOD(thread_p_Val2_1_fu_720_p2);
    sensitive << ( p_Val2_1_fu_720_p0 );
    sensitive << ( p_Val2_1_fu_720_p1 );

    SC_METHOD(thread_p_Val2_22_fu_450_p3);
    sensitive << ( closepath_reg_1081 );
    sensitive << ( tmp_12_i_i_reg_1129 );

    SC_METHOD(thread_p_Val2_2_fu_1027_p0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( p_Val2_2_fu_1027_p00 );

    SC_METHOD(thread_p_Val2_2_fu_1027_p00);
    sensitive << ( tmp_28_i_i_reg_1219 );

    SC_METHOD(thread_p_Val2_8_fu_465_p3);
    sensitive << ( p_Val2_6_reg_1123 );
    sensitive << ( tmp_23_fu_456_p1 );
    sensitive << ( p_Val2_i_i_fu_460_p2 );

    SC_METHOD(thread_p_Val2_i_i_fu_460_p2);
    sensitive << ( p_Val2_6_reg_1123 );

    SC_METHOD(thread_p_Val2_s_fu_322_p1);
    sensitive << ( x_load_reg_1057 );

    SC_METHOD(thread_p_i_i_fu_520_p2);
    sensitive << ( loc_V_reg_1068 );

    SC_METHOD(thread_r_V_1_fu_811_p2);
    sensitive << ( rhs_V_1_fu_807_p1 );

    SC_METHOD(thread_r_V_4_fu_389_p2);
    sensitive << ( ref_4oPi_table_100_V_q0 );
    sensitive << ( tmp_7_i_i_i_fu_386_p1 );

    SC_METHOD(thread_r_V_fu_772_p2);
    sensitive << ( p_Val2_16_fu_763_p2 );
    sensitive << ( tmp_36_i_i_cast_fu_769_p1 );

    SC_METHOD(thread_ref_4oPi_table_100_V_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_5_i_i_i_fu_377_p1 );

    SC_METHOD(thread_ref_4oPi_table_100_V_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_res_Addr_A);
    sensitive << ( res_Addr_A_orig );

    SC_METHOD(thread_res_Addr_A_orig);
    sensitive << ( tmp_s_reg_1047 );
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_res_Clk_A);
    sensitive << ( ap_clk );

    SC_METHOD(thread_res_Din_A);
    sensitive << ( tmp_1_reg_1304 );
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_res_EN_A);
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_res_Rst_A);
    sensitive << ( ap_rst_n_inv );

    SC_METHOD(thread_res_WEN_A);
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_ret_V_4_fu_978_p3);
    sensitive << ( tmp_13_fu_973_p2 );
    sensitive << ( p_Result_i_cast_fu_965_p3 );
    sensitive << ( loc_V_2_fu_830_p4 );

    SC_METHOD(thread_ret_V_5_fu_994_p3);
    sensitive << ( tmp_13_fu_973_p2 );
    sensitive << ( p_Result_1_i_cast_fu_986_p3 );
    sensitive << ( loc_V_3_fu_840_p1 );

    SC_METHOD(thread_rhs_V_1_fu_807_p1);
    sensitive << ( p_Ex_V_ret_i_fu_778_p3 );

    SC_METHOD(thread_second_order_float_2_address0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_29_i_i_fu_685_p1 );

    SC_METHOD(thread_second_order_float_2_ce0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_second_order_float_3_address0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_29_i_i_fu_685_p1 );

    SC_METHOD(thread_second_order_float_3_ce0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_second_order_float_s_address0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( tmp_29_i_i_fu_685_p1 );

    SC_METHOD(thread_second_order_float_s_ce0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_sh_assign_2_i_cast2_fu_595_p1);
    sensitive << ( sh_assign_reg_1168 );

    SC_METHOD(thread_sh_assign_2_i_cast_fu_598_p1);
    sensitive << ( sh_assign_reg_1168 );

    SC_METHOD(thread_sh_assign_fu_577_p3);
    sensitive << ( isNeg_fu_563_p3 );
    sensitive << ( sh_i_cast_fu_559_p1 );
    sensitive << ( tmp_18_i_i_fu_571_p2 );

    SC_METHOD(thread_sh_i_cast_fu_559_p1);
    sensitive << ( Ex_V_fu_553_p2 );

    SC_METHOD(thread_sin_basis_fu_671_p2);
    sensitive << ( cos_basis_fu_626_p10 );

    SC_METHOD(thread_ssdm_int_V_write_ass_fu_619_p3);
    sensitive << ( isNeg_reg_1163 );
    sensitive << ( tmp_20_i_i_cast_fu_609_p1 );
    sensitive << ( tmp_21_i_i_fu_613_p2 );

    SC_METHOD(thread_storemerge_i_i_fu_525_p3);
    sensitive << ( closepath_reg_1081 );
    sensitive << ( p_i_i_fu_520_p2 );

    SC_METHOD(thread_tmp_12_i_fu_926_p3);
    sensitive << ( cos_basis_reg_1187 );
    sensitive << ( tmp_fu_850_p18 );
    sensitive << ( tmp_12_fu_888_p18 );

    SC_METHOD(thread_tmp_13_fu_973_p2);
    sensitive << ( tmp_15_i_reg_1180 );
    sensitive << ( or_cond_i_fu_933_p2 );

    SC_METHOD(thread_tmp_13_i_fu_585_p2);
    sensitive << ( loc_V_reg_1068 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_tmp_13_i_i_fu_532_p1);
    sensitive << ( Mx_zeros_V_reg_1145 );

    SC_METHOD(thread_tmp_14_fu_367_p4);
    sensitive << ( addr_V_fu_359_p3 );

    SC_METHOD(thread_tmp_14_i_fu_425_p2);
    sensitive << ( loc_V_1_reg_1075 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_tmp_15_i_fu_590_p2);
    sensitive << ( loc_V_reg_1068 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_tmp_16_i_fu_942_p2);
    sensitive << ( tmp_15_i_reg_1180 );
    sensitive << ( tmp_12_i_fu_926_p3 );

    SC_METHOD(thread_tmp_16_i_i_fu_550_p1);
    sensitive << ( Mx_zeros_V_reg_1145 );

    SC_METHOD(thread_tmp_18_i_i_fu_571_p2);
    sensitive << ( sh_i_cast_fu_559_p1 );

    SC_METHOD(thread_tmp_19_i_i_fu_601_p1);
    sensitive << ( Mx_V_reg_1151 );

    SC_METHOD(thread_tmp_20_i_i_cast_fu_609_p1);
    sensitive << ( tmp_20_i_i_fu_604_p2 );

    SC_METHOD(thread_tmp_20_i_i_fu_604_p2);
    sensitive << ( Mx_V_reg_1151 );
    sensitive << ( sh_assign_2_i_cast_fu_598_p1 );

    SC_METHOD(thread_tmp_21_i_i_fu_613_p2);
    sensitive << ( tmp_19_i_i_fu_601_p1 );
    sensitive << ( sh_assign_2_i_cast2_fu_595_p1 );

    SC_METHOD(thread_tmp_22_fu_382_p1);
    sensitive << ( addr_V_fu_359_p3 );

    SC_METHOD(thread_tmp_23_fu_456_p1);
    sensitive << ( p_Val2_22_fu_450_p3 );

    SC_METHOD(thread_tmp_29_i_i_fu_685_p1);
    sensitive << ( p_Result_28_fu_677_p3 );

    SC_METHOD(thread_tmp_33_i_i_fu_757_p1);
    sensitive << ( p_Val2_15_reg_1224 );

    SC_METHOD(thread_tmp_34_i_i_fu_760_p1);
    sensitive << ( tmp_26_i_i_reg_1239 );

    SC_METHOD(thread_tmp_36_i_i_cast_fu_769_p1);
    sensitive << ( tmp_32_i_i_reg_1244 );

    SC_METHOD(thread_tmp_5_i_i_i_fu_377_p1);
    sensitive << ( tmp_14_fu_367_p4 );

    SC_METHOD(thread_tmp_7_i_i_i_fu_386_p1);
    sensitive << ( tmp_22_reg_1092 );

    SC_METHOD(thread_tmp_s_fu_317_p1);
    sensitive << ( i_reg_268 );

    SC_METHOD(thread_val_assign_fu_508_p3);
    sensitive << ( p_Result_27_fu_500_p3 );

    SC_METHOD(thread_x_Addr_A);
    sensitive << ( x_Addr_A_orig );

    SC_METHOD(thread_x_Addr_A_orig);
    sensitive << ( tmp_s_fu_317_p1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_x_Clk_A);
    sensitive << ( ap_clk );

    SC_METHOD(thread_x_Din_A);

    SC_METHOD(thread_x_EN_A);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_x_Rst_A);
    sensitive << ( ap_rst_n_inv );

    SC_METHOD(thread_x_WEN_A);

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( grp_scaled_fixed2ieee_fu_280_ap_done );
    sensitive << ( exitcond_fu_305_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const4);

    ap_CS_fsm = "00000000000000000000000000000001";
    grp_scaled_fixed2ieee_fu_280_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "mathFunction_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, x_Addr_A, "(port)x_Addr_A");
    sc_trace(mVcdFile, x_EN_A, "(port)x_EN_A");
    sc_trace(mVcdFile, x_WEN_A, "(port)x_WEN_A");
    sc_trace(mVcdFile, x_Din_A, "(port)x_Din_A");
    sc_trace(mVcdFile, x_Dout_A, "(port)x_Dout_A");
    sc_trace(mVcdFile, x_Clk_A, "(port)x_Clk_A");
    sc_trace(mVcdFile, x_Rst_A, "(port)x_Rst_A");
    sc_trace(mVcdFile, res_Addr_A, "(port)res_Addr_A");
    sc_trace(mVcdFile, res_EN_A, "(port)res_EN_A");
    sc_trace(mVcdFile, res_WEN_A, "(port)res_WEN_A");
    sc_trace(mVcdFile, res_Din_A, "(port)res_Din_A");
    sc_trace(mVcdFile, res_Dout_A, "(port)res_Dout_A");
    sc_trace(mVcdFile, res_Clk_A, "(port)res_Clk_A");
    sc_trace(mVcdFile, res_Rst_A, "(port)res_Rst_A");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWVALID, "(port)s_axi_CRTL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWREADY, "(port)s_axi_CRTL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_AWADDR, "(port)s_axi_CRTL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WVALID, "(port)s_axi_CRTL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WREADY, "(port)s_axi_CRTL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WDATA, "(port)s_axi_CRTL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_WSTRB, "(port)s_axi_CRTL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARVALID, "(port)s_axi_CRTL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARREADY, "(port)s_axi_CRTL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_ARADDR, "(port)s_axi_CRTL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RVALID, "(port)s_axi_CRTL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RREADY, "(port)s_axi_CRTL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RDATA, "(port)s_axi_CRTL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_RRESP, "(port)s_axi_CRTL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BVALID, "(port)s_axi_CRTL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BREADY, "(port)s_axi_CRTL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CRTL_BUS_BRESP, "(port)s_axi_CRTL_BUS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, y, "y");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_address0, "ref_4oPi_table_100_V_address0");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_ce0, "ref_4oPi_table_100_V_ce0");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_q0, "ref_4oPi_table_100_V_q0");
    sc_trace(mVcdFile, second_order_float_2_address0, "second_order_float_2_address0");
    sc_trace(mVcdFile, second_order_float_2_ce0, "second_order_float_2_ce0");
    sc_trace(mVcdFile, second_order_float_2_q0, "second_order_float_2_q0");
    sc_trace(mVcdFile, second_order_float_3_address0, "second_order_float_3_address0");
    sc_trace(mVcdFile, second_order_float_3_ce0, "second_order_float_3_ce0");
    sc_trace(mVcdFile, second_order_float_3_q0, "second_order_float_3_q0");
    sc_trace(mVcdFile, second_order_float_s_address0, "second_order_float_s_address0");
    sc_trace(mVcdFile, second_order_float_s_ce0, "second_order_float_s_ce0");
    sc_trace(mVcdFile, second_order_float_s_q0, "second_order_float_s_q0");
    sc_trace(mVcdFile, y_read_reg_1034, "y_read_reg_1034");
    sc_trace(mVcdFile, i_2_fu_311_p2, "i_2_fu_311_p2");
    sc_trace(mVcdFile, i_2_reg_1042, "i_2_reg_1042");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_s_fu_317_p1, "tmp_s_fu_317_p1");
    sc_trace(mVcdFile, tmp_s_reg_1047, "tmp_s_reg_1047");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, x_load_reg_1057, "x_load_reg_1057");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, results_sign_V_1_reg_1062, "results_sign_V_1_reg_1062");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, loc_V_fu_333_p4, "loc_V_fu_333_p4");
    sc_trace(mVcdFile, loc_V_reg_1068, "loc_V_reg_1068");
    sc_trace(mVcdFile, loc_V_1_fu_343_p1, "loc_V_1_fu_343_p1");
    sc_trace(mVcdFile, loc_V_1_reg_1075, "loc_V_1_reg_1075");
    sc_trace(mVcdFile, closepath_fu_347_p2, "closepath_fu_347_p2");
    sc_trace(mVcdFile, closepath_reg_1081, "closepath_reg_1081");
    sc_trace(mVcdFile, tmp_22_fu_382_p1, "tmp_22_fu_382_p1");
    sc_trace(mVcdFile, tmp_22_reg_1092, "tmp_22_reg_1092");
    sc_trace(mVcdFile, Med_V_reg_1097, "Med_V_reg_1097");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_14_i_fu_425_p2, "tmp_14_i_fu_425_p2");
    sc_trace(mVcdFile, tmp_14_i_reg_1112, "tmp_14_i_reg_1112");
    sc_trace(mVcdFile, grp_fu_300_p2, "grp_fu_300_p2");
    sc_trace(mVcdFile, x_assign_reg_1118, "x_assign_reg_1118");
    sc_trace(mVcdFile, p_Val2_6_reg_1123, "p_Val2_6_reg_1123");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_12_i_i_reg_1129, "tmp_12_i_i_reg_1129");
    sc_trace(mVcdFile, p_Val2_22_fu_450_p3, "p_Val2_22_fu_450_p3");
    sc_trace(mVcdFile, p_Val2_22_reg_1134, "p_Val2_22_reg_1134");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, p_Val2_8_fu_465_p3, "p_Val2_8_fu_465_p3");
    sc_trace(mVcdFile, p_Val2_8_reg_1140, "p_Val2_8_reg_1140");
    sc_trace(mVcdFile, Mx_zeros_V_fu_516_p1, "Mx_zeros_V_fu_516_p1");
    sc_trace(mVcdFile, Mx_zeros_V_reg_1145, "Mx_zeros_V_reg_1145");
    sc_trace(mVcdFile, Mx_V_reg_1151, "Mx_V_reg_1151");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, Ex_V_fu_553_p2, "Ex_V_fu_553_p2");
    sc_trace(mVcdFile, Ex_V_reg_1158, "Ex_V_reg_1158");
    sc_trace(mVcdFile, isNeg_fu_563_p3, "isNeg_fu_563_p3");
    sc_trace(mVcdFile, isNeg_reg_1163, "isNeg_reg_1163");
    sc_trace(mVcdFile, sh_assign_fu_577_p3, "sh_assign_fu_577_p3");
    sc_trace(mVcdFile, sh_assign_reg_1168, "sh_assign_reg_1168");
    sc_trace(mVcdFile, tmp_13_i_fu_585_p2, "tmp_13_i_fu_585_p2");
    sc_trace(mVcdFile, tmp_13_i_reg_1174, "tmp_13_i_reg_1174");
    sc_trace(mVcdFile, tmp_15_i_fu_590_p2, "tmp_15_i_fu_590_p2");
    sc_trace(mVcdFile, tmp_15_i_reg_1180, "tmp_15_i_reg_1180");
    sc_trace(mVcdFile, cos_basis_fu_626_p10, "cos_basis_fu_626_p10");
    sc_trace(mVcdFile, cos_basis_reg_1187, "cos_basis_reg_1187");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, p_Val2_12_fu_657_p1, "p_Val2_12_fu_657_p1");
    sc_trace(mVcdFile, p_Val2_12_reg_1194, "p_Val2_12_reg_1194");
    sc_trace(mVcdFile, tmp_i1_i_reg_1199, "tmp_i1_i_reg_1199");
    sc_trace(mVcdFile, tmp_28_i_i_reg_1219, "tmp_28_i_i_reg_1219");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, p_Val2_15_reg_1224, "p_Val2_15_reg_1224");
    sc_trace(mVcdFile, second_order_float_6_reg_1229, "second_order_float_6_reg_1229");
    sc_trace(mVcdFile, second_order_float_8_reg_1234, "second_order_float_8_reg_1234");
    sc_trace(mVcdFile, tmp_26_i_i_reg_1239, "tmp_26_i_i_reg_1239");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, tmp_32_i_i_reg_1244, "tmp_32_i_i_reg_1244");
    sc_trace(mVcdFile, Mx_V_read_assign_fu_751_p3, "Mx_V_read_assign_fu_751_p3");
    sc_trace(mVcdFile, Mx_V_read_assign_reg_1249, "Mx_V_read_assign_reg_1249");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, r_V_fu_772_p2, "r_V_fu_772_p2");
    sc_trace(mVcdFile, r_V_reg_1254, "r_V_reg_1254");
    sc_trace(mVcdFile, result_V_reg_1259, "result_V_reg_1259");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, r_V_1_fu_811_p2, "r_V_1_fu_811_p2");
    sc_trace(mVcdFile, r_V_1_reg_1264, "r_V_1_reg_1264");
    sc_trace(mVcdFile, or_cond_i_fu_933_p2, "or_cond_i_fu_933_p2");
    sc_trace(mVcdFile, or_cond_i_reg_1269, "or_cond_i_reg_1269");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_280_ap_idle, "grp_scaled_fixed2ieee_fu_280_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_280_ap_ready, "grp_scaled_fixed2ieee_fu_280_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_280_ap_done, "grp_scaled_fixed2ieee_fu_280_ap_done");
    sc_trace(mVcdFile, p_Result_i_fu_947_p3, "p_Result_i_fu_947_p3");
    sc_trace(mVcdFile, p_Result_i_reg_1274, "p_Result_i_reg_1274");
    sc_trace(mVcdFile, ret_V_4_fu_978_p3, "ret_V_4_fu_978_p3");
    sc_trace(mVcdFile, ret_V_4_reg_1279, "ret_V_4_reg_1279");
    sc_trace(mVcdFile, ret_V_5_fu_994_p3, "ret_V_5_fu_994_p3");
    sc_trace(mVcdFile, ret_V_5_reg_1284, "ret_V_5_reg_1284");
    sc_trace(mVcdFile, grp_fu_295_p2, "grp_fu_295_p2");
    sc_trace(mVcdFile, tmp_i_reg_1289, "tmp_i_reg_1289");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, grp_fu_286_p2, "grp_fu_286_p2");
    sc_trace(mVcdFile, tmp_9_reg_1299, "tmp_9_reg_1299");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, grp_fu_290_p2, "grp_fu_290_p2");
    sc_trace(mVcdFile, tmp_1_reg_1304, "tmp_1_reg_1304");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_280_ap_start, "grp_scaled_fixed2ieee_fu_280_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_280_ap_return, "grp_scaled_fixed2ieee_fu_280_ap_return");
    sc_trace(mVcdFile, i_reg_268, "i_reg_268");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_280_ap_start_reg, "grp_scaled_fixed2ieee_fu_280_ap_start_reg");
    sc_trace(mVcdFile, tmp_5_i_i_i_fu_377_p1, "tmp_5_i_i_i_fu_377_p1");
    sc_trace(mVcdFile, tmp_29_i_i_fu_685_p1, "tmp_29_i_i_fu_685_p1");
    sc_trace(mVcdFile, x_Addr_A_orig, "x_Addr_A_orig");
    sc_trace(mVcdFile, res_Addr_A_orig, "res_Addr_A_orig");
    sc_trace(mVcdFile, grp_fu_286_p0, "grp_fu_286_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_Val2_s_fu_322_p1, "p_Val2_s_fu_322_p1");
    sc_trace(mVcdFile, expv_op_i_fu_353_p2, "expv_op_i_fu_353_p2");
    sc_trace(mVcdFile, addr_V_fu_359_p3, "addr_V_fu_359_p3");
    sc_trace(mVcdFile, tmp_14_fu_367_p4, "tmp_14_fu_367_p4");
    sc_trace(mVcdFile, tmp_7_i_i_i_fu_386_p1, "tmp_7_i_i_i_fu_386_p1");
    sc_trace(mVcdFile, r_V_4_fu_389_p2, "r_V_4_fu_389_p2");
    sc_trace(mVcdFile, p_Result_24_fu_405_p3, "p_Result_24_fu_405_p3");
    sc_trace(mVcdFile, grp_fu_419_p0, "grp_fu_419_p0");
    sc_trace(mVcdFile, grp_fu_419_p1, "grp_fu_419_p1");
    sc_trace(mVcdFile, grp_fu_419_p2, "grp_fu_419_p2");
    sc_trace(mVcdFile, tmp_23_fu_456_p1, "tmp_23_fu_456_p1");
    sc_trace(mVcdFile, p_Val2_i_i_fu_460_p2, "p_Val2_i_i_fu_460_p2");
    sc_trace(mVcdFile, p_Result_i2_i_i_fu_472_p4, "p_Result_i2_i_i_fu_472_p4");
    sc_trace(mVcdFile, p_Result_25_fu_482_p3, "p_Result_25_fu_482_p3");
    sc_trace(mVcdFile, p_Result_26_fu_490_p4, "p_Result_26_fu_490_p4");
    sc_trace(mVcdFile, p_Result_27_fu_500_p3, "p_Result_27_fu_500_p3");
    sc_trace(mVcdFile, val_assign_fu_508_p3, "val_assign_fu_508_p3");
    sc_trace(mVcdFile, p_i_i_fu_520_p2, "p_i_i_fu_520_p2");
    sc_trace(mVcdFile, tmp_13_i_i_fu_532_p1, "tmp_13_i_i_fu_532_p1");
    sc_trace(mVcdFile, p_Val2_11_fu_535_p2, "p_Val2_11_fu_535_p2");
    sc_trace(mVcdFile, storemerge_i_i_fu_525_p3, "storemerge_i_i_fu_525_p3");
    sc_trace(mVcdFile, tmp_16_i_i_fu_550_p1, "tmp_16_i_i_fu_550_p1");
    sc_trace(mVcdFile, sh_i_cast_fu_559_p1, "sh_i_cast_fu_559_p1");
    sc_trace(mVcdFile, tmp_18_i_i_fu_571_p2, "tmp_18_i_i_fu_571_p2");
    sc_trace(mVcdFile, sh_assign_2_i_cast_fu_598_p1, "sh_assign_2_i_cast_fu_598_p1");
    sc_trace(mVcdFile, tmp_20_i_i_fu_604_p2, "tmp_20_i_i_fu_604_p2");
    sc_trace(mVcdFile, tmp_19_i_i_fu_601_p1, "tmp_19_i_i_fu_601_p1");
    sc_trace(mVcdFile, sh_assign_2_i_cast2_fu_595_p1, "sh_assign_2_i_cast2_fu_595_p1");
    sc_trace(mVcdFile, tmp_20_i_i_cast_fu_609_p1, "tmp_20_i_i_cast_fu_609_p1");
    sc_trace(mVcdFile, tmp_21_i_i_fu_613_p2, "tmp_21_i_i_fu_613_p2");
    sc_trace(mVcdFile, ssdm_int_V_write_ass_fu_619_p3, "ssdm_int_V_write_ass_fu_619_p3");
    sc_trace(mVcdFile, sin_basis_fu_671_p2, "sin_basis_fu_671_p2");
    sc_trace(mVcdFile, p_Result_i_i_fu_647_p4, "p_Result_i_i_fu_647_p4");
    sc_trace(mVcdFile, p_Result_28_fu_677_p3, "p_Result_28_fu_677_p3");
    sc_trace(mVcdFile, p_Val2_13_fu_1020_p2, "p_Val2_13_fu_1020_p2");
    sc_trace(mVcdFile, p_Val2_1_fu_720_p0, "p_Val2_1_fu_720_p0");
    sc_trace(mVcdFile, p_Val2_1_fu_720_p1, "p_Val2_1_fu_720_p1");
    sc_trace(mVcdFile, p_Val2_1_fu_720_p2, "p_Val2_1_fu_720_p2");
    sc_trace(mVcdFile, p_Val2_2_fu_1027_p2, "p_Val2_2_fu_1027_p2");
    sc_trace(mVcdFile, tmp_33_i_i_fu_757_p1, "tmp_33_i_i_fu_757_p1");
    sc_trace(mVcdFile, tmp_34_i_i_fu_760_p1, "tmp_34_i_i_fu_760_p1");
    sc_trace(mVcdFile, p_Val2_16_fu_763_p2, "p_Val2_16_fu_763_p2");
    sc_trace(mVcdFile, tmp_36_i_i_cast_fu_769_p1, "tmp_36_i_i_cast_fu_769_p1");
    sc_trace(mVcdFile, p_Val2_17_fu_790_p0, "p_Val2_17_fu_790_p0");
    sc_trace(mVcdFile, p_Val2_17_fu_790_p1, "p_Val2_17_fu_790_p1");
    sc_trace(mVcdFile, p_Val2_17_fu_790_p2, "p_Val2_17_fu_790_p2");
    sc_trace(mVcdFile, p_Ex_V_ret_i_fu_778_p3, "p_Ex_V_ret_i_fu_778_p3");
    sc_trace(mVcdFile, rhs_V_1_fu_807_p1, "rhs_V_1_fu_807_p1");
    sc_trace(mVcdFile, p_Val2_18_fu_818_p1, "p_Val2_18_fu_818_p1");
    sc_trace(mVcdFile, p_Result_30_fu_844_p3, "p_Result_30_fu_844_p3");
    sc_trace(mVcdFile, tmp_fu_850_p18, "tmp_fu_850_p18");
    sc_trace(mVcdFile, tmp_12_fu_888_p18, "tmp_12_fu_888_p18");
    sc_trace(mVcdFile, tmp_12_i_fu_926_p3, "tmp_12_i_fu_926_p3");
    sc_trace(mVcdFile, tmp_16_i_fu_942_p2, "tmp_16_i_fu_942_p2");
    sc_trace(mVcdFile, not_tmp_i_fu_937_p2, "not_tmp_i_fu_937_p2");
    sc_trace(mVcdFile, p_Result_29_fu_822_p3, "p_Result_29_fu_822_p3");
    sc_trace(mVcdFile, not_or_cond_i_demorg_fu_955_p2, "not_or_cond_i_demorg_fu_955_p2");
    sc_trace(mVcdFile, not_or_cond_i_fu_959_p2, "not_or_cond_i_fu_959_p2");
    sc_trace(mVcdFile, tmp_13_fu_973_p2, "tmp_13_fu_973_p2");
    sc_trace(mVcdFile, p_Result_i_cast_fu_965_p3, "p_Result_i_cast_fu_965_p3");
    sc_trace(mVcdFile, loc_V_2_fu_830_p4, "loc_V_2_fu_830_p4");
    sc_trace(mVcdFile, p_Result_1_i_cast_fu_986_p3, "p_Result_1_i_cast_fu_986_p3");
    sc_trace(mVcdFile, loc_V_3_fu_840_p1, "loc_V_3_fu_840_p1");
    sc_trace(mVcdFile, p_Result_s_fu_1002_p3, "p_Result_s_fu_1002_p3");
    sc_trace(mVcdFile, p_Result_31_fu_1007_p4, "p_Result_31_fu_1007_p4");
    sc_trace(mVcdFile, p_Val2_13_fu_1020_p0, "p_Val2_13_fu_1020_p0");
    sc_trace(mVcdFile, OP1_V_3_fu_692_p1, "OP1_V_3_fu_692_p1");
    sc_trace(mVcdFile, p_Val2_13_fu_1020_p1, "p_Val2_13_fu_1020_p1");
    sc_trace(mVcdFile, p_Val2_2_fu_1027_p0, "p_Val2_2_fu_1027_p0");
    sc_trace(mVcdFile, grp_fu_295_ce, "grp_fu_295_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, exitcond_fu_305_p2, "exitcond_fu_305_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_419_p00, "grp_fu_419_p00");
    sc_trace(mVcdFile, grp_fu_419_p10, "grp_fu_419_p10");
    sc_trace(mVcdFile, p_Val2_17_fu_790_p10, "p_Val2_17_fu_790_p10");
    sc_trace(mVcdFile, p_Val2_1_fu_720_p10, "p_Val2_1_fu_720_p10");
    sc_trace(mVcdFile, p_Val2_2_fu_1027_p00, "p_Val2_2_fu_1027_p00");
#endif

    }
    mHdltvinHandle.open("mathFunction.hdltvin.dat");
    mHdltvoutHandle.open("mathFunction.hdltvout.dat");
}

mathFunction::~mathFunction() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete ref_4oPi_table_100_V_U;
    delete second_order_float_2_U;
    delete second_order_float_3_U;
    delete second_order_float_s_U;
    delete mathFunction_CRTL_BUS_s_axi_U;
    delete grp_scaled_fixed2ieee_fu_280;
    delete mathFunction_faddfYi_U3;
    delete mathFunction_fmulg8j_U4;
    delete mathFunction_fsqrhbi_U5;
    delete mathFunction_fexpibs_U6;
    delete mathFunction_mul_jbC_U7;
    delete mathFunction_mux_kbM_U8;
    delete mathFunction_mux_lbW_U9;
    delete mathFunction_mux_lbW_U10;
    delete mathFunction_mul_mb6_U11;
    delete mathFunction_mul_ncg_U12;
}

void mathFunction::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void mathFunction::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_0;
}

void mathFunction::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv1_0;
}

void mathFunction::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_3F000000;
}

void mathFunction::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv1_1;
}

void mathFunction::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_scaled_fixed2ieee_fu_280_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
            grp_scaled_fixed2ieee_fu_280_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_280_ap_ready.read())) {
            grp_scaled_fixed2ieee_fu_280_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        i_reg_268 = i_2_reg_1042.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_268 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        Ex_V_reg_1158 = Ex_V_fu_553_p2.read();
        Mx_V_reg_1151 = p_Val2_11_fu_535_p2.read().range(57, 29);
        isNeg_reg_1163 = Ex_V_fu_553_p2.read().range(7, 7);
        sh_assign_reg_1168 = sh_assign_fu_577_p3.read();
        tmp_13_i_reg_1174 = tmp_13_i_fu_585_p2.read();
        tmp_15_i_reg_1180 = tmp_15_i_fu_590_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Med_V_reg_1097 = r_V_4_fu_389_p2.read().range(99, 20);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        Mx_V_read_assign_reg_1249 = Mx_V_read_assign_fu_751_p3.read();
        r_V_reg_1254 = r_V_fu_772_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        Mx_zeros_V_reg_1145 = Mx_zeros_V_fu_516_p1.read();
        p_Val2_22_reg_1134 = p_Val2_22_fu_450_p3.read();
        p_Val2_8_reg_1140 = p_Val2_8_fu_465_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        closepath_reg_1081 = closepath_fu_347_p2.read();
        loc_V_1_reg_1075 = loc_V_1_fu_343_p1.read();
        loc_V_reg_1068 = p_Val2_s_fu_322_p1.read().range(30, 23);
        results_sign_V_1_reg_1062 = p_Val2_s_fu_322_p1.read().range(31, 31);
        tmp_22_reg_1092 = tmp_22_fu_382_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        cos_basis_reg_1187 = cos_basis_fu_626_p10.read();
        p_Val2_12_reg_1194 = p_Val2_12_fu_657_p1.read();
        tmp_i1_i_reg_1199 = ssdm_int_V_write_ass_fu_619_p3.read().range(21, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_2_reg_1042 = i_2_fu_311_p2.read();
    }
    if ((esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_280_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        or_cond_i_reg_1269 = or_cond_i_fu_933_p2.read();
        p_Result_i_reg_1274 = p_Result_i_fu_947_p3.read();
        ret_V_4_reg_1279 = ret_V_4_fu_978_p3.read();
        ret_V_5_reg_1284 = ret_V_5_fu_994_p3.read();
        tmp_i_reg_1289 = grp_fu_295_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        p_Val2_15_reg_1224 = second_order_float_2_q0.read().range(29, 1);
        second_order_float_6_reg_1229 = second_order_float_3_q0.read();
        second_order_float_8_reg_1234 = second_order_float_s_q0.read();
        tmp_28_i_i_reg_1219 = p_Val2_13_fu_1020_p2.read().range(29, 15);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        p_Val2_6_reg_1123 = grp_fu_419_p2.read().range(76, 19);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        r_V_1_reg_1264 = r_V_1_fu_811_p2.read();
        result_V_reg_1259 = p_Val2_17_fu_790_p2.read().range(57, 29);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(closepath_reg_1081.read(), ap_const_lv1_0))) {
        tmp_12_i_i_reg_1129 = grp_fu_419_p2.read().range(79, 77);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_14_i_reg_1112 = tmp_14_i_fu_425_p2.read();
        x_assign_reg_1118 = grp_fu_300_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        tmp_1_reg_1304 = grp_fu_290_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        tmp_26_i_i_reg_1239 = p_Val2_1_fu_720_p2.read().range(44, 23);
        tmp_32_i_i_reg_1244 = p_Val2_2_fu_1027_p2.read().range(29, 16);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        tmp_9_reg_1299 = grp_fu_286_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_s_reg_1047 = tmp_s_fu_317_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        x_load_reg_1057 = x_Dout_A.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        y_read_reg_1034 = y.read();
    }
}

void mathFunction::thread_Ex_V_fu_553_p2() {
    Ex_V_fu_553_p2 = (!storemerge_i_i_fu_525_p3.read().is_01() || !tmp_16_i_i_fu_550_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(storemerge_i_i_fu_525_p3.read()) - sc_biguint<8>(tmp_16_i_i_fu_550_p1.read()));
}

void mathFunction::thread_Mx_V_read_assign_fu_751_p3() {
    Mx_V_read_assign_fu_751_p3 = (!cos_basis_reg_1187.read()[0].is_01())? sc_lv<29>(): ((cos_basis_reg_1187.read()[0].to_bool())? ap_const_lv29_1FFFFFFF: Mx_V_reg_1151.read());
}

void mathFunction::thread_Mx_zeros_V_fu_516_p1() {
    Mx_zeros_V_fu_516_p1 = val_assign_fu_508_p3.read().range(5-1, 0);
}

void mathFunction::thread_OP1_V_3_fu_692_p1() {
    OP1_V_3_fu_692_p1 = esl_zext<30,15>(tmp_i1_i_reg_1199.read());
}

void mathFunction::thread_addr_V_fu_359_p3() {
    addr_V_fu_359_p3 = (!closepath_fu_347_p2.read()[0].is_01())? sc_lv<8>(): ((closepath_fu_347_p2.read()[0].to_bool())? ap_const_lv8_3F: expv_op_i_fu_353_p2.read());
}

void mathFunction::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void mathFunction::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void mathFunction::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void mathFunction::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void mathFunction::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void mathFunction::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void mathFunction::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void mathFunction::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void mathFunction::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void mathFunction::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void mathFunction::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void mathFunction::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void mathFunction::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void mathFunction::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void mathFunction::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void mathFunction::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void mathFunction::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void mathFunction::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void mathFunction::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void mathFunction::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void mathFunction::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void mathFunction::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void mathFunction::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void mathFunction::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void mathFunction::thread_ap_done() {
    if ((esl_seteq<1,1,1>(exitcond_fu_305_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void mathFunction::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void mathFunction::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond_fu_305_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void mathFunction::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void mathFunction::thread_closepath_fu_347_p2() {
    closepath_fu_347_p2 = (!loc_V_fu_333_p4.read().is_01() || !ap_const_lv8_7E.is_01())? sc_lv<1>(): (sc_biguint<8>(loc_V_fu_333_p4.read()) < sc_biguint<8>(ap_const_lv8_7E));
}

void mathFunction::thread_exitcond_fu_305_p2() {
    exitcond_fu_305_p2 = (!i_reg_268.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_268.read() == ap_const_lv7_64);
}

void mathFunction::thread_expv_op_i_fu_353_p2() {
    expv_op_i_fu_353_p2 = (!ap_const_lv8_C2.is_01() || !loc_V_fu_333_p4.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_C2) + sc_biguint<8>(loc_V_fu_333_p4.read()));
}

void mathFunction::thread_grp_fu_286_p0() {
    grp_fu_286_p0 = p_Result_31_fu_1007_p4.read();
}

void mathFunction::thread_grp_fu_295_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         (esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_280_ap_done.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        grp_fu_295_ce = ap_const_logic_1;
    } else {
        grp_fu_295_ce = ap_const_logic_0;
    }
}

void mathFunction::thread_grp_fu_419_p0() {
    grp_fu_419_p0 =  (sc_lv<80>) (grp_fu_419_p00.read());
}

void mathFunction::thread_grp_fu_419_p00() {
    grp_fu_419_p00 = esl_zext<104,80>(Med_V_reg_1097.read());
}

void mathFunction::thread_grp_fu_419_p1() {
    grp_fu_419_p1 =  (sc_lv<24>) (grp_fu_419_p10.read());
}

void mathFunction::thread_grp_fu_419_p10() {
    grp_fu_419_p10 = esl_zext<104,24>(p_Result_24_fu_405_p3.read());
}

void mathFunction::thread_grp_scaled_fixed2ieee_fu_280_ap_start() {
    grp_scaled_fixed2ieee_fu_280_ap_start = grp_scaled_fixed2ieee_fu_280_ap_start_reg.read();
}

void mathFunction::thread_i_2_fu_311_p2() {
    i_2_fu_311_p2 = (!i_reg_268.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_reg_268.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void mathFunction::thread_isNeg_fu_563_p3() {
    isNeg_fu_563_p3 = Ex_V_fu_553_p2.read().range(7, 7);
}

void mathFunction::thread_loc_V_1_fu_343_p1() {
    loc_V_1_fu_343_p1 = p_Val2_s_fu_322_p1.read().range(23-1, 0);
}

void mathFunction::thread_loc_V_2_fu_830_p4() {
    loc_V_2_fu_830_p4 = p_Val2_18_fu_818_p1.read().range(30, 23);
}

void mathFunction::thread_loc_V_3_fu_840_p1() {
    loc_V_3_fu_840_p1 = p_Val2_18_fu_818_p1.read().range(23-1, 0);
}

void mathFunction::thread_loc_V_fu_333_p4() {
    loc_V_fu_333_p4 = p_Val2_s_fu_322_p1.read().range(30, 23);
}

void mathFunction::thread_not_or_cond_i_demorg_fu_955_p2() {
    not_or_cond_i_demorg_fu_955_p2 = (tmp_13_i_reg_1174.read() & tmp_14_i_reg_1112.read());
}

void mathFunction::thread_not_or_cond_i_fu_959_p2() {
    not_or_cond_i_fu_959_p2 = (not_or_cond_i_demorg_fu_955_p2.read() ^ ap_const_lv1_1);
}

void mathFunction::thread_not_tmp_i_fu_937_p2() {
    not_tmp_i_fu_937_p2 = (tmp_15_i_reg_1180.read() ^ ap_const_lv1_1);
}

void mathFunction::thread_or_cond_i_fu_933_p2() {
    or_cond_i_fu_933_p2 = (tmp_13_i_reg_1174.read() & tmp_14_i_reg_1112.read());
}

void mathFunction::thread_p_Ex_V_ret_i_fu_778_p3() {
    p_Ex_V_ret_i_fu_778_p3 = (!cos_basis_reg_1187.read()[0].is_01())? sc_lv<8>(): ((cos_basis_reg_1187.read()[0].to_bool())? ap_const_lv8_0: Ex_V_reg_1158.read());
}

void mathFunction::thread_p_Result_1_i_cast_fu_986_p3() {
    p_Result_1_i_cast_fu_986_p3 = (!not_or_cond_i_fu_959_p2.read()[0].is_01())? sc_lv<23>(): ((not_or_cond_i_fu_959_p2.read()[0].to_bool())? ap_const_lv23_7FFFFF: ap_const_lv23_0);
}

void mathFunction::thread_p_Result_24_fu_405_p3() {
    p_Result_24_fu_405_p3 = esl_concat<1,23>(ap_const_lv1_1, loc_V_1_reg_1075.read());
}

void mathFunction::thread_p_Result_25_fu_482_p3() {
    p_Result_25_fu_482_p3 = esl_concat<29,1>(p_Result_i2_i_i_fu_472_p4.read(), ap_const_lv1_1);
}

void mathFunction::thread_p_Result_26_fu_490_p4() {
    p_Result_26_fu_490_p4 = p_Result_25_fu_482_p3.read().range(0, 29);
}

void mathFunction::thread_p_Result_27_fu_500_p3() {
    p_Result_27_fu_500_p3 = esl_concat<2,30>(ap_const_lv2_3, p_Result_26_fu_490_p4.read());
}

void mathFunction::thread_p_Result_28_fu_677_p3() {
    p_Result_28_fu_677_p3 = esl_concat<1,7>(sin_basis_fu_671_p2.read(), p_Result_i_i_fu_647_p4.read());
}

void mathFunction::thread_p_Result_29_fu_822_p3() {
    p_Result_29_fu_822_p3 = p_Val2_18_fu_818_p1.read().range(31, 31);
}

void mathFunction::thread_p_Result_30_fu_844_p3() {
    p_Result_30_fu_844_p3 = esl_concat<1,3>(results_sign_V_1_reg_1062.read(), p_Val2_22_reg_1134.read());
}

void mathFunction::thread_p_Result_31_fu_1007_p4() {
    p_Result_31_fu_1007_p4 = esl_concat<9,23>(esl_concat<1,8>(p_Result_s_fu_1002_p3.read(), ret_V_4_reg_1279.read()), ret_V_5_reg_1284.read());
}

void mathFunction::thread_p_Result_i2_i_i_fu_472_p4() {
    p_Result_i2_i_i_fu_472_p4 = p_Val2_8_fu_465_p3.read().range(57, 29);
}

void mathFunction::thread_p_Result_i_cast_fu_965_p3() {
    p_Result_i_cast_fu_965_p3 = (!not_or_cond_i_fu_959_p2.read()[0].is_01())? sc_lv<8>(): ((not_or_cond_i_fu_959_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void mathFunction::thread_p_Result_i_fu_947_p3() {
    p_Result_i_fu_947_p3 = (!tmp_16_i_fu_942_p2.read()[0].is_01())? sc_lv<1>(): ((tmp_16_i_fu_942_p2.read()[0].to_bool())? not_tmp_i_fu_937_p2.read(): p_Result_29_fu_822_p3.read());
}

void mathFunction::thread_p_Result_i_i_fu_647_p4() {
    p_Result_i_i_fu_647_p4 = ssdm_int_V_write_ass_fu_619_p3.read().range(28, 22);
}

void mathFunction::thread_p_Result_s_fu_1002_p3() {
    p_Result_s_fu_1002_p3 = (!or_cond_i_reg_1269.read()[0].is_01())? sc_lv<1>(): ((or_cond_i_reg_1269.read()[0].to_bool())? results_sign_V_1_reg_1062.read(): p_Result_i_reg_1274.read());
}

void mathFunction::thread_p_Val2_11_fu_535_p2() {
    p_Val2_11_fu_535_p2 = (!tmp_13_i_i_fu_532_p1.read().is_01())? sc_lv<58>(): p_Val2_8_reg_1140.read() << (unsigned short)tmp_13_i_i_fu_532_p1.read().to_uint();
}

void mathFunction::thread_p_Val2_12_fu_657_p1() {
    p_Val2_12_fu_657_p1 = ssdm_int_V_write_ass_fu_619_p3.read().range(22-1, 0);
}

void mathFunction::thread_p_Val2_13_fu_1020_p0() {
    p_Val2_13_fu_1020_p0 =  (sc_lv<15>) (OP1_V_3_fu_692_p1.read());
}

void mathFunction::thread_p_Val2_13_fu_1020_p1() {
    p_Val2_13_fu_1020_p1 =  (sc_lv<15>) (OP1_V_3_fu_692_p1.read());
}

void mathFunction::thread_p_Val2_16_fu_763_p2() {
    p_Val2_16_fu_763_p2 = (!tmp_33_i_i_fu_757_p1.read().is_01() || !tmp_34_i_i_fu_760_p1.read().is_01())? sc_lv<30>(): (sc_bigint<30>(tmp_33_i_i_fu_757_p1.read()) + sc_bigint<30>(tmp_34_i_i_fu_760_p1.read()));
}

void mathFunction::thread_p_Val2_17_fu_790_p0() {
    p_Val2_17_fu_790_p0 = r_V_reg_1254.read();
}

void mathFunction::thread_p_Val2_17_fu_790_p1() {
    p_Val2_17_fu_790_p1 =  (sc_lv<29>) (p_Val2_17_fu_790_p10.read());
}

void mathFunction::thread_p_Val2_17_fu_790_p10() {
    p_Val2_17_fu_790_p10 = esl_zext<58,29>(Mx_V_read_assign_reg_1249.read());
}

void mathFunction::thread_p_Val2_17_fu_790_p2() {
    p_Val2_17_fu_790_p2 = (!p_Val2_17_fu_790_p0.read().is_01() || !p_Val2_17_fu_790_p1.read().is_01())? sc_lv<58>(): sc_bigint<30>(p_Val2_17_fu_790_p0.read()) * sc_biguint<29>(p_Val2_17_fu_790_p1.read());
}

void mathFunction::thread_p_Val2_18_fu_818_p1() {
    p_Val2_18_fu_818_p1 = grp_scaled_fixed2ieee_fu_280_ap_return.read();
}

void mathFunction::thread_p_Val2_1_fu_720_p0() {
    p_Val2_1_fu_720_p0 = second_order_float_6_reg_1229.read();
}

void mathFunction::thread_p_Val2_1_fu_720_p1() {
    p_Val2_1_fu_720_p1 =  (sc_lv<22>) (p_Val2_1_fu_720_p10.read());
}

void mathFunction::thread_p_Val2_1_fu_720_p10() {
    p_Val2_1_fu_720_p10 = esl_zext<45,22>(p_Val2_12_reg_1194.read());
}

void mathFunction::thread_p_Val2_1_fu_720_p2() {
    p_Val2_1_fu_720_p2 = (!p_Val2_1_fu_720_p0.read().is_01() || !p_Val2_1_fu_720_p1.read().is_01())? sc_lv<45>(): sc_bigint<23>(p_Val2_1_fu_720_p0.read()) * sc_biguint<22>(p_Val2_1_fu_720_p1.read());
}

void mathFunction::thread_p_Val2_22_fu_450_p3() {
    p_Val2_22_fu_450_p3 = (!closepath_reg_1081.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_1081.read()[0].to_bool())? ap_const_lv3_0: tmp_12_i_i_reg_1129.read());
}

void mathFunction::thread_p_Val2_2_fu_1027_p0() {
    p_Val2_2_fu_1027_p0 =  (sc_lv<15>) (p_Val2_2_fu_1027_p00.read());
}

void mathFunction::thread_p_Val2_2_fu_1027_p00() {
    p_Val2_2_fu_1027_p00 = esl_zext<30,15>(tmp_28_i_i_reg_1219.read());
}

void mathFunction::thread_p_Val2_8_fu_465_p3() {
    p_Val2_8_fu_465_p3 = (!tmp_23_fu_456_p1.read()[0].is_01())? sc_lv<58>(): ((tmp_23_fu_456_p1.read()[0].to_bool())? p_Val2_i_i_fu_460_p2.read(): p_Val2_6_reg_1123.read());
}

void mathFunction::thread_p_Val2_i_i_fu_460_p2() {
    p_Val2_i_i_fu_460_p2 = (!ap_const_lv58_0.is_01() || !p_Val2_6_reg_1123.read().is_01())? sc_lv<58>(): (sc_biguint<58>(ap_const_lv58_0) - sc_biguint<58>(p_Val2_6_reg_1123.read()));
}

void mathFunction::thread_p_Val2_s_fu_322_p1() {
    p_Val2_s_fu_322_p1 = x_load_reg_1057.read();
}

void mathFunction::thread_p_i_i_fu_520_p2() {
    p_i_i_fu_520_p2 = (!ap_const_lv8_83.is_01() || !loc_V_reg_1068.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_83) + sc_biguint<8>(loc_V_reg_1068.read()));
}

void mathFunction::thread_r_V_1_fu_811_p2() {
    r_V_1_fu_811_p2 = (!ap_const_lv9_0.is_01() || !rhs_V_1_fu_807_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(rhs_V_1_fu_807_p1.read()));
}

void mathFunction::thread_r_V_4_fu_389_p2() {
    r_V_4_fu_389_p2 = (!tmp_7_i_i_i_fu_386_p1.read().is_01())? sc_lv<100>(): ref_4oPi_table_100_V_q0.read() << (unsigned short)tmp_7_i_i_i_fu_386_p1.read().to_uint();
}

void mathFunction::thread_r_V_fu_772_p2() {
    r_V_fu_772_p2 = (!p_Val2_16_fu_763_p2.read().is_01() || !tmp_36_i_i_cast_fu_769_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(p_Val2_16_fu_763_p2.read()) + sc_bigint<30>(tmp_36_i_i_cast_fu_769_p1.read()));
}

void mathFunction::thread_ref_4oPi_table_100_V_address0() {
    ref_4oPi_table_100_V_address0 =  (sc_lv<4>) (tmp_5_i_i_i_fu_377_p1.read());
}

void mathFunction::thread_ref_4oPi_table_100_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ref_4oPi_table_100_V_ce0 = ap_const_logic_1;
    } else {
        ref_4oPi_table_100_V_ce0 = ap_const_logic_0;
    }
}

void mathFunction::thread_res_Addr_A() {
    res_Addr_A = (!ap_const_lv32_2.is_01())? sc_lv<32>(): res_Addr_A_orig.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void mathFunction::thread_res_Addr_A_orig() {
    res_Addr_A_orig =  (sc_lv<32>) (tmp_s_reg_1047.read());
}

void mathFunction::thread_res_Clk_A() {
    res_Clk_A = ap_clk.read()? SC_LOGIC_1 : SC_LOGIC_0;
}

void mathFunction::thread_res_Din_A() {
    res_Din_A = tmp_1_reg_1304.read();
}

void mathFunction::thread_res_EN_A() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        res_EN_A = ap_const_logic_1;
    } else {
        res_EN_A = ap_const_logic_0;
    }
}

void mathFunction::thread_res_Rst_A() {
    res_Rst_A = ap_rst_n_inv.read();
}

void mathFunction::thread_res_WEN_A() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        res_WEN_A = ap_const_lv4_F;
    } else {
        res_WEN_A = ap_const_lv4_0;
    }
}

void mathFunction::thread_ret_V_4_fu_978_p3() {
    ret_V_4_fu_978_p3 = (!tmp_13_fu_973_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_13_fu_973_p2.read()[0].to_bool())? p_Result_i_cast_fu_965_p3.read(): loc_V_2_fu_830_p4.read());
}

void mathFunction::thread_ret_V_5_fu_994_p3() {
    ret_V_5_fu_994_p3 = (!tmp_13_fu_973_p2.read()[0].is_01())? sc_lv<23>(): ((tmp_13_fu_973_p2.read()[0].to_bool())? p_Result_1_i_cast_fu_986_p3.read(): loc_V_3_fu_840_p1.read());
}

void mathFunction::thread_rhs_V_1_fu_807_p1() {
    rhs_V_1_fu_807_p1 = esl_sext<9,8>(p_Ex_V_ret_i_fu_778_p3.read());
}

void mathFunction::thread_second_order_float_2_address0() {
    second_order_float_2_address0 =  (sc_lv<8>) (tmp_29_i_i_fu_685_p1.read());
}

void mathFunction::thread_second_order_float_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        second_order_float_2_ce0 = ap_const_logic_1;
    } else {
        second_order_float_2_ce0 = ap_const_logic_0;
    }
}

void mathFunction::thread_second_order_float_3_address0() {
    second_order_float_3_address0 =  (sc_lv<8>) (tmp_29_i_i_fu_685_p1.read());
}

void mathFunction::thread_second_order_float_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        second_order_float_3_ce0 = ap_const_logic_1;
    } else {
        second_order_float_3_ce0 = ap_const_logic_0;
    }
}

void mathFunction::thread_second_order_float_s_address0() {
    second_order_float_s_address0 =  (sc_lv<8>) (tmp_29_i_i_fu_685_p1.read());
}

void mathFunction::thread_second_order_float_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        second_order_float_s_ce0 = ap_const_logic_1;
    } else {
        second_order_float_s_ce0 = ap_const_logic_0;
    }
}

void mathFunction::thread_sh_assign_2_i_cast2_fu_595_p1() {
    sh_assign_2_i_cast2_fu_595_p1 = esl_sext<32,9>(sh_assign_reg_1168.read());
}

void mathFunction::thread_sh_assign_2_i_cast_fu_598_p1() {
    sh_assign_2_i_cast_fu_598_p1 = esl_sext<29,9>(sh_assign_reg_1168.read());
}

void mathFunction::thread_sh_assign_fu_577_p3() {
    sh_assign_fu_577_p3 = (!isNeg_fu_563_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_563_p3.read()[0].to_bool())? tmp_18_i_i_fu_571_p2.read(): sh_i_cast_fu_559_p1.read());
}

void mathFunction::thread_sh_i_cast_fu_559_p1() {
    sh_i_cast_fu_559_p1 = esl_sext<9,8>(Ex_V_fu_553_p2.read());
}

void mathFunction::thread_sin_basis_fu_671_p2() {
    sin_basis_fu_671_p2 = (cos_basis_fu_626_p10.read() ^ ap_const_lv1_1);
}

void mathFunction::thread_ssdm_int_V_write_ass_fu_619_p3() {
    ssdm_int_V_write_ass_fu_619_p3 = (!isNeg_reg_1163.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_1163.read()[0].to_bool())? tmp_20_i_i_cast_fu_609_p1.read(): tmp_21_i_i_fu_613_p2.read());
}

void mathFunction::thread_storemerge_i_i_fu_525_p3() {
    storemerge_i_i_fu_525_p3 = (!closepath_reg_1081.read()[0].is_01())? sc_lv<8>(): ((closepath_reg_1081.read()[0].to_bool())? p_i_i_fu_520_p2.read(): ap_const_lv8_0);
}

void mathFunction::thread_tmp_12_i_fu_926_p3() {
    tmp_12_i_fu_926_p3 = (!cos_basis_reg_1187.read()[0].is_01())? sc_lv<1>(): ((cos_basis_reg_1187.read()[0].to_bool())? tmp_fu_850_p18.read(): tmp_12_fu_888_p18.read());
}

void mathFunction::thread_tmp_13_fu_973_p2() {
    tmp_13_fu_973_p2 = (or_cond_i_fu_933_p2.read() | tmp_15_i_reg_1180.read());
}

void mathFunction::thread_tmp_13_i_fu_585_p2() {
    tmp_13_i_fu_585_p2 = (!loc_V_reg_1068.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1068.read() == ap_const_lv8_0);
}

void mathFunction::thread_tmp_13_i_i_fu_532_p1() {
    tmp_13_i_i_fu_532_p1 = esl_zext<58,5>(Mx_zeros_V_reg_1145.read());
}

void mathFunction::thread_tmp_14_fu_367_p4() {
    tmp_14_fu_367_p4 = addr_V_fu_359_p3.read().range(7, 4);
}

void mathFunction::thread_tmp_14_i_fu_425_p2() {
    tmp_14_i_fu_425_p2 = (!loc_V_1_reg_1075.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_1_reg_1075.read() == ap_const_lv23_0);
}

void mathFunction::thread_tmp_15_i_fu_590_p2() {
    tmp_15_i_fu_590_p2 = (!loc_V_reg_1068.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1068.read() == ap_const_lv8_FF);
}

void mathFunction::thread_tmp_16_i_fu_942_p2() {
    tmp_16_i_fu_942_p2 = (tmp_15_i_reg_1180.read() | tmp_12_i_fu_926_p3.read());
}

void mathFunction::thread_tmp_16_i_i_fu_550_p1() {
    tmp_16_i_i_fu_550_p1 = esl_zext<8,5>(Mx_zeros_V_reg_1145.read());
}

void mathFunction::thread_tmp_18_i_i_fu_571_p2() {
    tmp_18_i_i_fu_571_p2 = (!ap_const_lv9_0.is_01() || !sh_i_cast_fu_559_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_bigint<9>(sh_i_cast_fu_559_p1.read()));
}

void mathFunction::thread_tmp_19_i_i_fu_601_p1() {
    tmp_19_i_i_fu_601_p1 = esl_zext<32,29>(Mx_V_reg_1151.read());
}

void mathFunction::thread_tmp_20_i_i_cast_fu_609_p1() {
    tmp_20_i_i_cast_fu_609_p1 = esl_zext<32,29>(tmp_20_i_i_fu_604_p2.read());
}

void mathFunction::thread_tmp_20_i_i_fu_604_p2() {
    tmp_20_i_i_fu_604_p2 = (!sh_assign_2_i_cast_fu_598_p1.read().is_01())? sc_lv<29>(): Mx_V_reg_1151.read() >> (unsigned short)sh_assign_2_i_cast_fu_598_p1.read().to_uint();
}

void mathFunction::thread_tmp_21_i_i_fu_613_p2() {
    tmp_21_i_i_fu_613_p2 = (!sh_assign_2_i_cast2_fu_595_p1.read().is_01())? sc_lv<32>(): tmp_19_i_i_fu_601_p1.read() << (unsigned short)sh_assign_2_i_cast2_fu_595_p1.read().to_uint();
}

void mathFunction::thread_tmp_22_fu_382_p1() {
    tmp_22_fu_382_p1 = addr_V_fu_359_p3.read().range(4-1, 0);
}

void mathFunction::thread_tmp_23_fu_456_p1() {
    tmp_23_fu_456_p1 = p_Val2_22_fu_450_p3.read().range(1-1, 0);
}

void mathFunction::thread_tmp_29_i_i_fu_685_p1() {
    tmp_29_i_i_fu_685_p1 = esl_zext<64,8>(p_Result_28_fu_677_p3.read());
}

void mathFunction::thread_tmp_33_i_i_fu_757_p1() {
    tmp_33_i_i_fu_757_p1 = esl_sext<30,29>(p_Val2_15_reg_1224.read());
}

void mathFunction::thread_tmp_34_i_i_fu_760_p1() {
    tmp_34_i_i_fu_760_p1 = esl_sext<30,22>(tmp_26_i_i_reg_1239.read());
}

void mathFunction::thread_tmp_36_i_i_cast_fu_769_p1() {
    tmp_36_i_i_cast_fu_769_p1 = esl_sext<30,14>(tmp_32_i_i_reg_1244.read());
}

void mathFunction::thread_tmp_5_i_i_i_fu_377_p1() {
    tmp_5_i_i_i_fu_377_p1 = esl_zext<64,4>(tmp_14_fu_367_p4.read());
}

void mathFunction::thread_tmp_7_i_i_i_fu_386_p1() {
    tmp_7_i_i_i_fu_386_p1 = esl_zext<100,4>(tmp_22_reg_1092.read());
}

void mathFunction::thread_tmp_s_fu_317_p1() {
    tmp_s_fu_317_p1 = esl_zext<64,7>(i_reg_268.read());
}

void mathFunction::thread_val_assign_fu_508_p3() {
    val_assign_fu_508_p3 = esl_cttz<32,32>(p_Result_27_fu_500_p3.read());
}

void mathFunction::thread_x_Addr_A() {
    x_Addr_A = (!ap_const_lv32_2.is_01())? sc_lv<32>(): x_Addr_A_orig.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void mathFunction::thread_x_Addr_A_orig() {
    x_Addr_A_orig =  (sc_lv<32>) (tmp_s_fu_317_p1.read());
}

void mathFunction::thread_x_Clk_A() {
    x_Clk_A = ap_clk.read()? SC_LOGIC_1 : SC_LOGIC_0;
}

void mathFunction::thread_x_Din_A() {
    x_Din_A = ap_const_lv32_0;
}

void mathFunction::thread_x_EN_A() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        x_EN_A = ap_const_logic_1;
    } else {
        x_EN_A = ap_const_logic_0;
    }
}

void mathFunction::thread_x_Rst_A() {
    x_Rst_A = ap_rst_n_inv.read();
}

void mathFunction::thread_x_WEN_A() {
    x_WEN_A = ap_const_lv4_0;
}

void mathFunction::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_305_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            if ((esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_280_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
                ap_NS_fsm = ap_ST_fsm_state23;
            } else {
                ap_NS_fsm = ap_ST_fsm_state22;
            }
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

void mathFunction::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"x_Addr_A\" :  \"" << x_Addr_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_EN_A\" :  \"" << x_EN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_WEN_A\" :  \"" << x_WEN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_Din_A\" :  \"" << x_Din_A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x_Dout_A\" :  \"" << x_Dout_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_Clk_A\" :  \"" << x_Clk_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"x_Rst_A\" :  \"" << x_Rst_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_Addr_A\" :  \"" << res_Addr_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_EN_A\" :  \"" << res_EN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_WEN_A\" :  \"" << res_WEN_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_Din_A\" :  \"" << res_Din_A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"res_Dout_A\" :  \"" << res_Dout_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_Clk_A\" :  \"" << res_Clk_A.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_Rst_A\" :  \"" << res_Rst_A.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_AWVALID\" :  \"" << s_axi_CRTL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_AWREADY\" :  \"" << s_axi_CRTL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_AWADDR\" :  \"" << s_axi_CRTL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WVALID\" :  \"" << s_axi_CRTL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_WREADY\" :  \"" << s_axi_CRTL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WDATA\" :  \"" << s_axi_CRTL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_WSTRB\" :  \"" << s_axi_CRTL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_ARVALID\" :  \"" << s_axi_CRTL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_ARREADY\" :  \"" << s_axi_CRTL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_ARADDR\" :  \"" << s_axi_CRTL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RVALID\" :  \"" << s_axi_CRTL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_RREADY\" :  \"" << s_axi_CRTL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RDATA\" :  \"" << s_axi_CRTL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_RRESP\" :  \"" << s_axi_CRTL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_BVALID\" :  \"" << s_axi_CRTL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CRTL_BUS_BREADY\" :  \"" << s_axi_CRTL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CRTL_BUS_BRESP\" :  \"" << s_axi_CRTL_BUS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

