// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "scaled_fixed2ieee.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic scaled_fixed2ieee::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic scaled_fixed2ieee::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state1 = "1";
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state2 = "10";
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state3 = "100";
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state4 = "1000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1 = "1";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_0 = "0";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_2 = "10";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_0 = "00";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3 = "11";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_1 = "1";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_D = "1101";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1C = "11100";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_F = "1111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1F = "11111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_12 = "10010";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_2 = "10";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_1 = "1";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_10 = "10000";
const sc_lv<9> scaled_fixed2ieee::ap_const_lv9_7F = "1111111";
const sc_lv<29> scaled_fixed2ieee::ap_const_lv29_0 = "00000000000000000000000000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_5 = "101";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1B = "11011";
const sc_lv<23> scaled_fixed2ieee::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<8> scaled_fixed2ieee::ap_const_lv8_0 = "00000000";
const bool scaled_fixed2ieee::ap_const_boolean_1 = true;

scaled_fixed2ieee::scaled_fixed2ieee(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_p_Val2_s_phi_fu_159_p4);
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( in_shift_V_reg_520 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_Val2_s_reg_156 );

    SC_METHOD(thread_ap_phi_mux_shift_1_phi_fu_169_p4);
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( shift_2_reg_514 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( shift_1_reg_166 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( result_write_assign_fu_462_p1 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_c_0_fu_272_p3);
    sensitive << ( p_Result_2_fu_264_p3 );

    SC_METHOD(thread_c_1_1_fu_280_p3);
    sensitive << ( c_0_s_reg_88 );
    sensitive << ( tmp_3_fu_242_p1 );
    sensitive << ( c_0_fu_272_p3 );

    SC_METHOD(thread_c_1_2_fu_288_p3);
    sensitive << ( c_1_s_reg_100 );
    sensitive << ( tmp_3_fu_242_p1 );
    sensitive << ( c_0_fu_272_p3 );

    SC_METHOD(thread_exitcond_fu_230_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i1_reg_112 );

    SC_METHOD(thread_i_1_fu_304_p2);
    sensitive << ( i2_reg_145 );

    SC_METHOD(thread_i_fu_236_p2);
    sensitive << ( i1_reg_112 );

    SC_METHOD(thread_in_shift_V_fu_374_p3);
    sensitive << ( isNeg_fu_328_p3 );
    sensitive << ( tmp_15_fu_366_p1 );
    sensitive << ( tmp_16_fu_370_p1 );

    SC_METHOD(thread_isNeg_fu_328_p3);
    sensitive << ( sh_assign_fu_314_p3 );

    SC_METHOD(thread_newexp_fu_397_p2);
    sensitive << ( ap_phi_mux_shift_1_phi_fu_169_p4 );
    sensitive << ( tmp_1_cast_fu_393_p1 );

    SC_METHOD(thread_or_cond_fu_416_p2);
    sensitive << ( tmp_18_fu_403_p3 );
    sensitive << ( tmp_8_fu_411_p2 );

    SC_METHOD(thread_out_bits_0_V_fu_194_p5);
    sensitive << ( tmp_fu_186_p3 );

    SC_METHOD(thread_out_exp_V_fu_444_p3);
    sensitive << ( or_cond_fu_416_p2 );
    sensitive << ( tmp_19_fu_422_p1 );

    SC_METHOD(thread_p_Result_1_fu_176_p4);
    sensitive << ( in_V );

    SC_METHOD(thread_p_Result_2_fu_264_p3);
    sensitive << ( tmp_3_fu_242_p1 );
    sensitive << ( tmp_10_fu_246_p4 );
    sensitive << ( tmp_11_fu_255_p4 );

    SC_METHOD(thread_p_Result_3_fu_452_p4);
    sensitive << ( out_exp_V_fu_444_p3 );
    sensitive << ( p_Val2_1_fu_436_p3 );

    SC_METHOD(thread_p_Result_s_fu_218_p5);
    sensitive << ( tmp_4_fu_210_p3 );

    SC_METHOD(thread_p_Val2_1_fu_436_p3);
    sensitive << ( or_cond_fu_416_p2 );
    sensitive << ( phitmp2_fu_426_p4 );

    SC_METHOD(thread_phitmp2_fu_426_p4);
    sensitive << ( ap_phi_mux_p_Val2_s_phi_fu_159_p4 );

    SC_METHOD(thread_result_write_assign_fu_462_p1);
    sensitive << ( p_Result_3_fu_452_p4 );

    SC_METHOD(thread_sh_assign_1_fu_342_p3);
    sensitive << ( sh_assign_fu_314_p3 );
    sensitive << ( isNeg_fu_328_p3 );
    sensitive << ( tmp_5_fu_336_p2 );

    SC_METHOD(thread_sh_assign_fu_314_p3);
    sensitive << ( c_0_s_reg_88 );
    sensitive << ( c_1_s_reg_100 );
    sensitive << ( tmp_13_fu_310_p1 );

    SC_METHOD(thread_shift_2_fu_322_p2);
    sensitive << ( shift_reg_133 );
    sensitive << ( sh_assign_fu_314_p3 );

    SC_METHOD(thread_tmp_10_fu_246_p4);
    sensitive << ( p_Result_s_reg_482 );

    SC_METHOD(thread_tmp_11_fu_255_p4);
    sensitive << ( out_bits_0_V_reg_477 );

    SC_METHOD(thread_tmp_12_fu_296_p3);
    sensitive << ( i2_reg_145 );

    SC_METHOD(thread_tmp_13_fu_310_p1);
    sensitive << ( i2_reg_145 );

    SC_METHOD(thread_tmp_15_fu_366_p1);
    sensitive << ( tmp_7_fu_360_p2 );

    SC_METHOD(thread_tmp_16_fu_370_p1);
    sensitive << ( tmp_9_fu_354_p2 );

    SC_METHOD(thread_tmp_18_fu_403_p3);
    sensitive << ( newexp_fu_397_p2 );

    SC_METHOD(thread_tmp_19_fu_422_p1);
    sensitive << ( newexp_fu_397_p2 );

    SC_METHOD(thread_tmp_1_cast_fu_393_p1);
    sensitive << ( tmp_1_fu_388_p2 );

    SC_METHOD(thread_tmp_1_fu_388_p2);
    sensitive << ( prescale );

    SC_METHOD(thread_tmp_2_fu_206_p1);
    sensitive << ( in_V );

    SC_METHOD(thread_tmp_3_fu_242_p1);
    sensitive << ( i1_reg_112 );

    SC_METHOD(thread_tmp_4_fu_210_p3);
    sensitive << ( tmp_2_fu_206_p1 );

    SC_METHOD(thread_tmp_5_fu_336_p2);
    sensitive << ( sh_assign_fu_314_p3 );

    SC_METHOD(thread_tmp_6_fu_350_p1);
    sensitive << ( in_shift_reg_123 );

    SC_METHOD(thread_tmp_7_fu_360_p2);
    sensitive << ( tmp_6_fu_350_p1 );
    sensitive << ( sh_assign_1_fu_342_p3 );

    SC_METHOD(thread_tmp_8_fu_411_p2);
    sensitive << ( in_V );
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_tmp_9_fu_354_p2);
    sensitive << ( tmp_6_fu_350_p1 );
    sensitive << ( sh_assign_1_fu_342_p3 );

    SC_METHOD(thread_tmp_fu_186_p3);
    sensitive << ( p_Result_1_fu_176_p4 );

    SC_METHOD(thread_tmp_s_fu_382_p2);
    sensitive << ( tmp_12_fu_296_p3 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sh_assign_fu_314_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_230_p2 );
    sensitive << ( tmp_12_reg_505 );
    sensitive << ( tmp_s_reg_526 );
    sensitive << ( ap_CS_fsm_state4 );

    ap_CS_fsm = "0001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "scaled_fixed2ieee_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V, "(port)in_V");
    sc_trace(mVcdFile, prescale, "(port)prescale");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_bits_0_V_fu_194_p5, "out_bits_0_V_fu_194_p5");
    sc_trace(mVcdFile, out_bits_0_V_reg_477, "out_bits_0_V_reg_477");
    sc_trace(mVcdFile, p_Result_s_fu_218_p5, "p_Result_s_fu_218_p5");
    sc_trace(mVcdFile, p_Result_s_reg_482, "p_Result_s_reg_482");
    sc_trace(mVcdFile, i_fu_236_p2, "i_fu_236_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, c_1_1_fu_280_p3, "c_1_1_fu_280_p3");
    sc_trace(mVcdFile, exitcond_fu_230_p2, "exitcond_fu_230_p2");
    sc_trace(mVcdFile, c_1_2_fu_288_p3, "c_1_2_fu_288_p3");
    sc_trace(mVcdFile, tmp_12_fu_296_p3, "tmp_12_fu_296_p3");
    sc_trace(mVcdFile, tmp_12_reg_505, "tmp_12_reg_505");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_1_fu_304_p2, "i_1_fu_304_p2");
    sc_trace(mVcdFile, i_1_reg_509, "i_1_reg_509");
    sc_trace(mVcdFile, shift_2_fu_322_p2, "shift_2_fu_322_p2");
    sc_trace(mVcdFile, shift_2_reg_514, "shift_2_reg_514");
    sc_trace(mVcdFile, in_shift_V_fu_374_p3, "in_shift_V_fu_374_p3");
    sc_trace(mVcdFile, in_shift_V_reg_520, "in_shift_V_reg_520");
    sc_trace(mVcdFile, tmp_s_fu_382_p2, "tmp_s_fu_382_p2");
    sc_trace(mVcdFile, tmp_s_reg_526, "tmp_s_reg_526");
    sc_trace(mVcdFile, c_0_s_reg_88, "c_0_s_reg_88");
    sc_trace(mVcdFile, c_1_s_reg_100, "c_1_s_reg_100");
    sc_trace(mVcdFile, i1_reg_112, "i1_reg_112");
    sc_trace(mVcdFile, in_shift_reg_123, "in_shift_reg_123");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, shift_reg_133, "shift_reg_133");
    sc_trace(mVcdFile, i2_reg_145, "i2_reg_145");
    sc_trace(mVcdFile, ap_phi_mux_p_Val2_s_phi_fu_159_p4, "ap_phi_mux_p_Val2_s_phi_fu_159_p4");
    sc_trace(mVcdFile, p_Val2_s_reg_156, "p_Val2_s_reg_156");
    sc_trace(mVcdFile, ap_phi_mux_shift_1_phi_fu_169_p4, "ap_phi_mux_shift_1_phi_fu_169_p4");
    sc_trace(mVcdFile, shift_1_reg_166, "shift_1_reg_166");
    sc_trace(mVcdFile, p_Result_1_fu_176_p4, "p_Result_1_fu_176_p4");
    sc_trace(mVcdFile, tmp_fu_186_p3, "tmp_fu_186_p3");
    sc_trace(mVcdFile, tmp_2_fu_206_p1, "tmp_2_fu_206_p1");
    sc_trace(mVcdFile, tmp_4_fu_210_p3, "tmp_4_fu_210_p3");
    sc_trace(mVcdFile, tmp_3_fu_242_p1, "tmp_3_fu_242_p1");
    sc_trace(mVcdFile, tmp_10_fu_246_p4, "tmp_10_fu_246_p4");
    sc_trace(mVcdFile, tmp_11_fu_255_p4, "tmp_11_fu_255_p4");
    sc_trace(mVcdFile, p_Result_2_fu_264_p3, "p_Result_2_fu_264_p3");
    sc_trace(mVcdFile, c_0_fu_272_p3, "c_0_fu_272_p3");
    sc_trace(mVcdFile, tmp_13_fu_310_p1, "tmp_13_fu_310_p1");
    sc_trace(mVcdFile, sh_assign_fu_314_p3, "sh_assign_fu_314_p3");
    sc_trace(mVcdFile, isNeg_fu_328_p3, "isNeg_fu_328_p3");
    sc_trace(mVcdFile, tmp_5_fu_336_p2, "tmp_5_fu_336_p2");
    sc_trace(mVcdFile, tmp_6_fu_350_p1, "tmp_6_fu_350_p1");
    sc_trace(mVcdFile, sh_assign_1_fu_342_p3, "sh_assign_1_fu_342_p3");
    sc_trace(mVcdFile, tmp_7_fu_360_p2, "tmp_7_fu_360_p2");
    sc_trace(mVcdFile, tmp_9_fu_354_p2, "tmp_9_fu_354_p2");
    sc_trace(mVcdFile, tmp_15_fu_366_p1, "tmp_15_fu_366_p1");
    sc_trace(mVcdFile, tmp_16_fu_370_p1, "tmp_16_fu_370_p1");
    sc_trace(mVcdFile, tmp_1_fu_388_p2, "tmp_1_fu_388_p2");
    sc_trace(mVcdFile, tmp_1_cast_fu_393_p1, "tmp_1_cast_fu_393_p1");
    sc_trace(mVcdFile, newexp_fu_397_p2, "newexp_fu_397_p2");
    sc_trace(mVcdFile, tmp_18_fu_403_p3, "tmp_18_fu_403_p3");
    sc_trace(mVcdFile, tmp_8_fu_411_p2, "tmp_8_fu_411_p2");
    sc_trace(mVcdFile, or_cond_fu_416_p2, "or_cond_fu_416_p2");
    sc_trace(mVcdFile, phitmp2_fu_426_p4, "phitmp2_fu_426_p4");
    sc_trace(mVcdFile, tmp_19_fu_422_p1, "tmp_19_fu_422_p1");
    sc_trace(mVcdFile, out_exp_V_fu_444_p3, "out_exp_V_fu_444_p3");
    sc_trace(mVcdFile, p_Val2_1_fu_436_p3, "p_Val2_1_fu_436_p3");
    sc_trace(mVcdFile, p_Result_3_fu_452_p4, "p_Result_3_fu_452_p4");
    sc_trace(mVcdFile, result_write_assign_fu_462_p1, "result_write_assign_fu_462_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

scaled_fixed2ieee::~scaled_fixed2ieee() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void scaled_fixed2ieee::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
             (esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_1) || 
              esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0)))) {
            ap_return_preg = result_write_assign_fu_462_p1.read();
        }
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_230_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i1_reg_112 = i_fu_236_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i1_reg_112 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_230_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i2_reg_145 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i2_reg_145 = i_1_reg_509.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_230_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        in_shift_reg_123 = in_V.read();
    } else if ((esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        in_shift_reg_123 = in_shift_V_reg_520.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0))) {
        p_Val2_s_reg_156 = in_shift_V_reg_520.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(tmp_12_fu_296_p3.read(), ap_const_lv1_1))) {
        p_Val2_s_reg_156 = in_shift_reg_123.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0))) {
        shift_1_reg_166 = shift_2_reg_514.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(tmp_12_fu_296_p3.read(), ap_const_lv1_1))) {
        shift_1_reg_166 = shift_reg_133.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_230_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        shift_reg_133 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        shift_reg_133 = shift_2_reg_514.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_230_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        c_0_s_reg_88 = c_1_1_fu_280_p3.read();
        c_1_s_reg_100 = c_1_2_fu_288_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_1_reg_509 = i_1_fu_304_p2.read();
        tmp_12_reg_505 = i2_reg_145.read().range(1, 1);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_12_fu_296_p3.read()))) {
        in_shift_V_reg_520 = in_shift_V_fu_374_p3.read();
        shift_2_reg_514 = shift_2_fu_322_p2.read();
        tmp_s_reg_526 = tmp_s_fu_382_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        out_bits_0_V_reg_477 = out_bits_0_V_fu_194_p5.read();
        p_Result_s_reg_482 = p_Result_s_fu_218_p5.read();
    }
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void scaled_fixed2ieee::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          (esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_1) || 
           esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_phi_mux_p_Val2_s_phi_fu_159_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0))) {
        ap_phi_mux_p_Val2_s_phi_fu_159_p4 = in_shift_V_reg_520.read();
    } else {
        ap_phi_mux_p_Val2_s_phi_fu_159_p4 = p_Val2_s_reg_156.read();
    }
}

void scaled_fixed2ieee::thread_ap_phi_mux_shift_1_phi_fu_169_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0))) {
        ap_phi_mux_shift_1_phi_fu_169_p4 = shift_2_reg_514.read();
    } else {
        ap_phi_mux_shift_1_phi_fu_169_p4 = shift_1_reg_166.read();
    }
}

void scaled_fixed2ieee::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         (esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         (esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0)))) {
        ap_return = result_write_assign_fu_462_p1.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void scaled_fixed2ieee::thread_c_0_fu_272_p3() {
    c_0_fu_272_p3 = esl_cttz<32,32>(p_Result_2_fu_264_p3.read());
}

void scaled_fixed2ieee::thread_c_1_1_fu_280_p3() {
    c_1_1_fu_280_p3 = (!tmp_3_fu_242_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_242_p1.read()[0].to_bool())? c_0_s_reg_88.read(): c_0_fu_272_p3.read());
}

void scaled_fixed2ieee::thread_c_1_2_fu_288_p3() {
    c_1_2_fu_288_p3 = (!tmp_3_fu_242_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_242_p1.read()[0].to_bool())? c_0_fu_272_p3.read(): c_1_s_reg_100.read());
}

void scaled_fixed2ieee::thread_exitcond_fu_230_p2() {
    exitcond_fu_230_p2 = (!i1_reg_112.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_112.read() == ap_const_lv2_2);
}

void scaled_fixed2ieee::thread_i_1_fu_304_p2() {
    i_1_fu_304_p2 = (!i2_reg_145.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i2_reg_145.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_i_fu_236_p2() {
    i_fu_236_p2 = (!i1_reg_112.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_reg_112.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_in_shift_V_fu_374_p3() {
    in_shift_V_fu_374_p3 = (!isNeg_fu_328_p3.read()[0].is_01())? sc_lv<29>(): ((isNeg_fu_328_p3.read()[0].to_bool())? tmp_15_fu_366_p1.read(): tmp_16_fu_370_p1.read());
}

void scaled_fixed2ieee::thread_isNeg_fu_328_p3() {
    isNeg_fu_328_p3 = sh_assign_fu_314_p3.read().range(31, 31);
}

void scaled_fixed2ieee::thread_newexp_fu_397_p2() {
    newexp_fu_397_p2 = (!tmp_1_cast_fu_393_p1.read().is_01() || !ap_phi_mux_shift_1_phi_fu_169_p4.read().is_01())? sc_lv<32>(): (sc_bigint<32>(tmp_1_cast_fu_393_p1.read()) - sc_biguint<32>(ap_phi_mux_shift_1_phi_fu_169_p4.read()));
}

void scaled_fixed2ieee::thread_or_cond_fu_416_p2() {
    or_cond_fu_416_p2 = (tmp_18_fu_403_p3.read() | tmp_8_fu_411_p2.read());
}

void scaled_fixed2ieee::thread_out_bits_0_V_fu_194_p5() {
    out_bits_0_V_fu_194_p5 = esl_partset<32,32,17,32,32>(ap_const_lv32_0, tmp_fu_186_p3.read(), ap_const_lv32_F, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_out_exp_V_fu_444_p3() {
    out_exp_V_fu_444_p3 = (!or_cond_fu_416_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond_fu_416_p2.read()[0].to_bool())? ap_const_lv8_0: tmp_19_fu_422_p1.read());
}

void scaled_fixed2ieee::thread_p_Result_1_fu_176_p4() {
    p_Result_1_fu_176_p4 = in_V.read().range(28, 13);
}

void scaled_fixed2ieee::thread_p_Result_2_fu_264_p3() {
    p_Result_2_fu_264_p3 = (!tmp_3_fu_242_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_242_p1.read()[0].to_bool())? tmp_10_fu_246_p4.read(): tmp_11_fu_255_p4.read());
}

void scaled_fixed2ieee::thread_p_Result_3_fu_452_p4() {
    p_Result_3_fu_452_p4 = esl_concat<9,23>(esl_concat<1,8>(ap_const_lv1_0, out_exp_V_fu_444_p3.read()), p_Val2_1_fu_436_p3.read());
}

void scaled_fixed2ieee::thread_p_Result_s_fu_218_p5() {
    p_Result_s_fu_218_p5 = esl_partset<32,32,14,32,32>(ap_const_lv32_0, tmp_4_fu_210_p3.read(), ap_const_lv32_12, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_p_Val2_1_fu_436_p3() {
    p_Val2_1_fu_436_p3 = (!or_cond_fu_416_p2.read()[0].is_01())? sc_lv<23>(): ((or_cond_fu_416_p2.read()[0].to_bool())? ap_const_lv23_0: phitmp2_fu_426_p4.read());
}

void scaled_fixed2ieee::thread_phitmp2_fu_426_p4() {
    phitmp2_fu_426_p4 = ap_phi_mux_p_Val2_s_phi_fu_159_p4.read().range(27, 5);
}

void scaled_fixed2ieee::thread_result_write_assign_fu_462_p1() {
    result_write_assign_fu_462_p1 = p_Result_3_fu_452_p4.read();
}

void scaled_fixed2ieee::thread_sh_assign_1_fu_342_p3() {
    sh_assign_1_fu_342_p3 = (!isNeg_fu_328_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_328_p3.read()[0].to_bool())? tmp_5_fu_336_p2.read(): sh_assign_fu_314_p3.read());
}

void scaled_fixed2ieee::thread_sh_assign_fu_314_p3() {
    sh_assign_fu_314_p3 = (!tmp_13_fu_310_p1.read()[0].is_01())? sc_lv<32>(): ((tmp_13_fu_310_p1.read()[0].to_bool())? c_1_s_reg_100.read(): c_0_s_reg_88.read());
}

void scaled_fixed2ieee::thread_shift_2_fu_322_p2() {
    shift_2_fu_322_p2 = (!shift_reg_133.read().is_01() || !sh_assign_fu_314_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(shift_reg_133.read()) + sc_biguint<32>(sh_assign_fu_314_p3.read()));
}

void scaled_fixed2ieee::thread_tmp_10_fu_246_p4() {
    tmp_10_fu_246_p4 = p_Result_s_reg_482.read().range(0, 31);
}

void scaled_fixed2ieee::thread_tmp_11_fu_255_p4() {
    tmp_11_fu_255_p4 = out_bits_0_V_reg_477.read().range(0, 31);
}

void scaled_fixed2ieee::thread_tmp_12_fu_296_p3() {
    tmp_12_fu_296_p3 = i2_reg_145.read().range(1, 1);
}

void scaled_fixed2ieee::thread_tmp_13_fu_310_p1() {
    tmp_13_fu_310_p1 = i2_reg_145.read().range(1-1, 0);
}

void scaled_fixed2ieee::thread_tmp_15_fu_366_p1() {
    tmp_15_fu_366_p1 = tmp_7_fu_360_p2.read().range(29-1, 0);
}

void scaled_fixed2ieee::thread_tmp_16_fu_370_p1() {
    tmp_16_fu_370_p1 = tmp_9_fu_354_p2.read().range(29-1, 0);
}

void scaled_fixed2ieee::thread_tmp_18_fu_403_p3() {
    tmp_18_fu_403_p3 = newexp_fu_397_p2.read().range(31, 31);
}

void scaled_fixed2ieee::thread_tmp_19_fu_422_p1() {
    tmp_19_fu_422_p1 = newexp_fu_397_p2.read().range(8-1, 0);
}

void scaled_fixed2ieee::thread_tmp_1_cast_fu_393_p1() {
    tmp_1_cast_fu_393_p1 = esl_sext<32,9>(tmp_1_fu_388_p2.read());
}

void scaled_fixed2ieee::thread_tmp_1_fu_388_p2() {
    tmp_1_fu_388_p2 = (!ap_const_lv9_7F.is_01() || !prescale.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_7F) - sc_biguint<9>(prescale.read()));
}

void scaled_fixed2ieee::thread_tmp_2_fu_206_p1() {
    tmp_2_fu_206_p1 = in_V.read().range(13-1, 0);
}

void scaled_fixed2ieee::thread_tmp_3_fu_242_p1() {
    tmp_3_fu_242_p1 = i1_reg_112.read().range(1-1, 0);
}

void scaled_fixed2ieee::thread_tmp_4_fu_210_p3() {
    tmp_4_fu_210_p3 = esl_concat<13,1>(tmp_2_fu_206_p1.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_5_fu_336_p2() {
    tmp_5_fu_336_p2 = (!ap_const_lv32_0.is_01() || !sh_assign_fu_314_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(sh_assign_fu_314_p3.read()));
}

void scaled_fixed2ieee::thread_tmp_6_fu_350_p1() {
    tmp_6_fu_350_p1 = esl_zext<32,29>(in_shift_reg_123.read());
}

void scaled_fixed2ieee::thread_tmp_7_fu_360_p2() {
    tmp_7_fu_360_p2 = (!sh_assign_1_fu_342_p3.read().is_01())? sc_lv<32>(): tmp_6_fu_350_p1.read() >> (unsigned short)sh_assign_1_fu_342_p3.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_8_fu_411_p2() {
    tmp_8_fu_411_p2 = (!in_V.read().is_01() || !ap_const_lv29_0.is_01())? sc_lv<1>(): sc_lv<1>(in_V.read() == ap_const_lv29_0);
}

void scaled_fixed2ieee::thread_tmp_9_fu_354_p2() {
    tmp_9_fu_354_p2 = (!sh_assign_1_fu_342_p3.read().is_01())? sc_lv<32>(): tmp_6_fu_350_p1.read() << (unsigned short)sh_assign_1_fu_342_p3.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_fu_186_p3() {
    tmp_fu_186_p3 = esl_concat<16,1>(p_Result_1_fu_176_p4.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_s_fu_382_p2() {
    tmp_s_fu_382_p2 = (!sh_assign_fu_314_p3.read().is_01() || !ap_const_lv32_10.is_01())? sc_lv<1>(): sc_lv<1>(sh_assign_fu_314_p3.read() == ap_const_lv32_10);
}

void scaled_fixed2ieee::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_230_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && (esl_seteq<1,1,1>(tmp_12_reg_505.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_s_reg_526.read(), ap_const_lv1_0)))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

