// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "ximageprocess.h"

extern XImageprocess_Config XImageprocess_ConfigTable[];

XImageprocess_Config *XImageprocess_LookupConfig(u16 DeviceId) {
	XImageprocess_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XIMAGEPROCESS_NUM_INSTANCES; Index++) {
		if (XImageprocess_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XImageprocess_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XImageprocess_Initialize(XImageprocess *InstancePtr, u16 DeviceId) {
	XImageprocess_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XImageprocess_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XImageprocess_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

