// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XIMAGEPROCESS_H
#define XIMAGEPROCESS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "ximageprocess_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Kernel_bus_BaseAddress;
    u32 Crtl_bus_BaseAddress;
} XImageprocess_Config;
#endif

typedef struct {
    u32 Kernel_bus_BaseAddress;
    u32 Crtl_bus_BaseAddress;
    u32 IsReady;
} XImageprocess;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XImageprocess_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XImageprocess_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XImageprocess_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XImageprocess_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XImageprocess_Initialize(XImageprocess *InstancePtr, u16 DeviceId);
XImageprocess_Config* XImageprocess_LookupConfig(u16 DeviceId);
int XImageprocess_CfgInitialize(XImageprocess *InstancePtr, XImageprocess_Config *ConfigPtr);
#else
int XImageprocess_Initialize(XImageprocess *InstancePtr, const char* InstanceName);
int XImageprocess_Release(XImageprocess *InstancePtr);
#endif

void XImageprocess_Start(XImageprocess *InstancePtr);
u32 XImageprocess_IsDone(XImageprocess *InstancePtr);
u32 XImageprocess_IsIdle(XImageprocess *InstancePtr);
u32 XImageprocess_IsReady(XImageprocess *InstancePtr);
void XImageprocess_EnableAutoRestart(XImageprocess *InstancePtr);
void XImageprocess_DisableAutoRestart(XImageprocess *InstancePtr);

void XImageprocess_Set_operation(XImageprocess *InstancePtr, u32 Data);
u32 XImageprocess_Get_operation(XImageprocess *InstancePtr);
u32 XImageprocess_Get_kernel_BaseAddress(XImageprocess *InstancePtr);
u32 XImageprocess_Get_kernel_HighAddress(XImageprocess *InstancePtr);
u32 XImageprocess_Get_kernel_TotalBytes(XImageprocess *InstancePtr);
u32 XImageprocess_Get_kernel_BitWidth(XImageprocess *InstancePtr);
u32 XImageprocess_Get_kernel_Depth(XImageprocess *InstancePtr);
u32 XImageprocess_Write_kernel_Words(XImageprocess *InstancePtr, int offset, int *data, int length);
u32 XImageprocess_Read_kernel_Words(XImageprocess *InstancePtr, int offset, int *data, int length);
u32 XImageprocess_Write_kernel_Bytes(XImageprocess *InstancePtr, int offset, char *data, int length);
u32 XImageprocess_Read_kernel_Bytes(XImageprocess *InstancePtr, int offset, char *data, int length);

void XImageprocess_InterruptGlobalEnable(XImageprocess *InstancePtr);
void XImageprocess_InterruptGlobalDisable(XImageprocess *InstancePtr);
void XImageprocess_InterruptEnable(XImageprocess *InstancePtr, u32 Mask);
void XImageprocess_InterruptDisable(XImageprocess *InstancePtr, u32 Mask);
void XImageprocess_InterruptClear(XImageprocess *InstancePtr, u32 Mask);
u32 XImageprocess_InterruptGetEnabled(XImageprocess *InstancePtr);
u32 XImageprocess_InterruptGetStatus(XImageprocess *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
